### ISSUE TITLE
restapi : file 업로드

### ISSUE THREAD

**Issue by ChaeyunBae** [RD101/dotori#1004]
#597

**Comment by ChaeyunBae** [comment]
## 한 번의 Request에 ascii 데이터 + binary 파일을 함께 post 하는 방법
-  multipart/mixed : 다른 "Content-type" 헤더를 갖는 파일을 전송하는 데 사용.
ex) e

#### Reference
- https://ko.wikipedia.org/wiki/MIME

## ascii를 먼저 request 하고 restapi 안에서 file upload request를 한 번 더 보내는 방법
- ```file=/home/chaeyun.bae/app/dotori/test.png&file1=/homefdf/dga/df/dtest.abc``` 
input path를 ascii 데이터 post 할 때 추가해야 함

**Comment by ChaeyunBae** [comment]
## 방법2) ascii를 먼저 request 하고 restapi 안에서 file upload request를 한 번 더 보내는 방법
- ```file=/home/chaeyun.bae/app/dotori/test.png&file1=/homefdf/dga/df/dtest.abc``` 
input path를 ascii 데이터 post 할 때 추가해야 함

**Comment by ChaeyunBae** [comment]
## 방법3) ascii를 먼저 request 하고 restapi 안에서 file upload request를 한 번 더 보냄
- ```file=/home/chaeyun.bae/app/dotori/test.png&file1=/homefdf/dga/df/dtest.abc``` 
input path를 ascii 데이터 post 할 때 추가해야 함

**Comment by khw7096** [comment]
오~~

**Comment by ChaeyunBae** [comment]
- curl로 file을 전송할 때 mov, abc의 mimetype이 application/octet-stream으로 찍힌다
https://stackoverflow.com/questions/13484478/curl-per-file-content-type-for-multipart-post-youtube-api

**Comment by ChaeyunBae** [comment]
mimetype은 그냥 수동으로 쓰기로!
