### ISSUE TITLE
도움! : curl 을 이용해서 server에 요청을 보낼 때(post)  data의 value 값에 map 형식으로 데이터를 넣을 수 있을까요??

### ISSUE THREAD

**Issue by ChaeyunBae** [RD101/dotori#1011]
restapi 이용해서  asset 등록하는 기능(#1003) 추가 중인데요!

```
curl -H "Authorization: Basic <Token>" -X POST -d "itemtype=maya&title=train&author=dchecheb&description=test&tags=test3 test2 test1" http://172.18.18.22/api/item
```
이런식으로 itemtype, title, author, description, tags 보내는 건 성공했는데 attributes는 어떻게 보내야할지 모르겠어요.

**Comment by baesy0** [comment]
```...&attribute="key:value key:value key:value"```
는 어때요?
그런 다음 위 문자를 파싱해서 map에 넣어주는 것도 방법일 거 같아요

**Comment by ChaeyunBae** [comment]
> `...&attribute="key:value key:value key:value"`
> 는 어때요?
> 그런 다음 위 문자를 파싱해서 map에 넣어주는 것도 방법일 거 같아요

이렇게 한번 해볼게요!

**Comment by baesy0** [comment]
ㅇㅇ!
1. 띄어쓰기 기준으로 나누기
1. `:`기준으로 나누기
```go
for _, attr := range strings.Split(attributes, " "){
    key, value := strings.Split(attr, ":")
    map[key] = value
}
```

**Comment by khw7096** [comment]
저도 위 의견에 동의해요. curl은 문자열만 보낼 수 있다고 생각하고 짜면되요.
