### ISSUE TITLE
addMayaItemCmd 리팩토링: 시간 지정하는 부분 삭제

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#1026]
https://github.com/RD101/dotori/blob/00cedd76c9f0f650b9e8eaffe68a0c511c13939d/command.go#L49
위 코드는 없어져도 된다.

AddItem함수에서 Item을 DB에 넣을 때 createtime과 updatetime을 설정해주고 있기 때문이다.
https://github.com/RD101/dotori/blob/00cedd76c9f0f650b9e8eaffe68a0c511c13939d/dbapi.go#L16

**Comment by khw7096** [comment]
동의~!
