### ISSUE TITLE
REST API:attribute 파싱할 때 아래 함수를 이용하면 될 거 같아요!

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#1044]
https://github.com/RD101/dotori/blob/dbfc683f6c3755b239f04297b0cd673d13a92ddb/stringfunc.go#L26

**Comment by ChaeyunBae** [comment]
오!

**Comment by baesy0** [comment]
과거의 우리는 열심히 만들어 둔 게 있었다...

**Comment by baesy0** [comment]
#1058 이슈 토의 결과에 따라 달라질 거 같아요

**Comment by khw7096** [comment]
이 이슈는 정보공유 이슈이기 때문에 닫습니다.
