### ISSUE TITLE
cmd: inputpath가 regular파일이 아닌 경우 걸러내기

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#1051]

**Comment by baesy0** [comment]
symbolic만 체크하기보다는 regular인지 아닌지를 체크하는 편이 좋을 거 같다.

**Comment by baesy0** [comment]
### thumbnail 이미지
- symlink를 넘겨줘도 processing에는 문제가 없다.
- 다만 symlink의 이름이 `.jpg` `.png`로 끝나지 않으면 에러처리에서 걸린다.
```go
// command.go
ext := filepath.Ext(*flagInputThumbImgPath)
	if ext != ".jpg" && ext != ".png" {
		log.Fatal("지원하지 않는 썸네일 이미지 포맷입니다.")
}
```
- 따라서 symlink를 허용할거면 symlink인 경우를 검출해서 따로 에러처리해야 한다.
```go
// 아마 이런 구조이지 않을까
if input path == 심볼링링크{
    // 심볼링링크가 가리키고 있는 경로를 가져온다
    // 해당 경로의 확장자를 검사한다.
}
```

**Comment by baesy0** [comment]
### data
-  위와 같은 문제 + copyFile함수 내부에서 regular파일이 아닌 경우를 걸러내고 있다.

따라서 symlink를 사용할 수 없다.

**Comment by baesy0** [comment]
일단 regular파일이 아닌 것은 모두 걸러내기로!
추후 regular파일은 아니지만 허용이 필요한 경우 추가한다.

**Comment by khw7096** [comment]
동의합니다.
