### ISSUE TITLE
cmd: 파일명 혹은 폴더명에 띄어쓰기가 있는 경우 에러처리 하기

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#1053]
- [x] "strings" 패턴 찾기
- [x] 'string' 패턴 찾기
- [x] 문자열로 경로 패턴 뽑기

**Comment by khw7096** [comment]
리눅스에서 먼저 사용된다고 생각하고 작성하기.

**Comment by baesy0** [comment]
사례
```
/rd/project/seq/tt df/test/test.ma
/rd/project/onset/현장에서 모델링 한 파일/onset.mb
```

**Comment by baesy0** [comment]
### try1
- 경로는 무조건 따옴표로 감싼다
- 경로가 2개 이상일 경우 각 경로는 작은 따옴표로, 전체 값은 큰 따옴표로 감싼다.

**Comment by khw7096** [comment]
아래 3가지 경우가 있다고 합니다.
https://stackoverflow.com/questions/12902227/how-to-input-a-path-with-a-white-space

```
SOME_PATH="/mnt/someProject/some path"
SOME_PATH='/mnt/someProject/some path'
SOME_PATH=/mnt/someProject/some\ path
```

**Comment by baesy0** [comment]
1. 경로 분리
1. 각 경로가 경로 레귤러 익스프레션과 맞는지 체크

**Comment by khw7096** [comment]
https://www.golangprograms.com/regular-expressions.html

**Comment by khw7096** [comment]
pathfunc에 선언하고 테스트 코드 작성하기.

**Comment by khw7096** [comment]
https://stackoverflow.com/questions/56798431/find-byte-offset-of-a-pattern-in-golang

**Comment by khw7096** [comment]
![image](https://user-images.githubusercontent.com/1149996/91656705-c880e900-eaf5-11ea-857a-b310c058d7f3.png)

**Comment by khw7096** [comment]
준비물은 완료.

**Comment by khw7096** [comment]
테스트 코드 완료.

**Comment by khw7096** [comment]
실제 코드랑 물리는 것만 남음. 이 이슈를 닫습니다.
