### ISSUE TITLE
,(comma) vs " "(space)

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#1058]
dotori전반에서 사용할 기준을 정합시다.
1. 콤마
1. 공백
1. 콤마 + 공백

**Comment by ChaeyunBae** [comment]
사용자 기준에서 가장 편한 건 '나비,구름' or '나비 구름' or  '나비, 구름' 이 세 가지 형식 모두 가능한 거일 것 같아요

**Comment by baesy0** [comment]
command나 REST API의 경우는 단일 기준으로 통일하는게 좋을 거 같아요.

**Comment by baesy0** [comment]
- 사용자
- command, REST API
이렇게 나눠서 생각해볼 수도 있겠네요

**Comment by khw7096** [comment]
저도 콤마와 스페이스를 둘다 지원하는게 사용자 입장에서 가장 편해보여요~

**Comment by ChaeyunBae** [comment]
같은 함수로 파싱하면 restapi나 command에서도 세 가지 형식 다 지원할 수 있지 않을까요??

**Comment by khw7096** [comment]
다른 오류 가능성을 체크할 필요가 있지만 채윤님 의견에 동의합니다. testcode를 빡쎄게 쳐보면 더 안도될 것 같아요.

**Comment by baesy0** [comment]
### reference
https://help.gooddata.com/doc/en/building-on-gooddata-platform/data-preparation-and-distribution/additional-data-load-reference/data-load-tutorials/loading-data-via-rest-api

**Comment by baesy0** [comment]
- 레퍼런스 수집
- 스페이스와 콤마를 사용하는 부분이 어디인지.

**Comment by khw7096** [comment]
str2tags
