### ISSUE TITLE
검색 할 때 'tag:test'든 'tag: test'든 둘 다 가능하게 하기

### ISSUE THREAD

**Issue by ChaeyunBae** [RD101/dotori#1061]
```
strings.TrimSpace()
```
이용하면 가능할 것 같아욤

**Comment by baesy0** [comment]
좋아요:)

**Comment by khw7096** [comment]
+2

**Comment by khw7096** [comment]
이 방식은 좋은 느낌이 안들어요.

![image](https://user-images.githubusercontent.com/1149996/89282268-3f0d0100-d686-11ea-9704-63c95bef6186.png)

![image](https://user-images.githubusercontent.com/1149996/89282319-521fd100-d686-11ea-9a9d-d5b72e287c39.png)

위 아래 검색은 엄연하게 달라요.
깃허브도 이 방식을 지원하지 않아요. 띄어쓰기로 filter기능을 할 수 있기 때문에..

**Comment by khw7096** [comment]
저는 조심스레~ 반대에 한표합니다.

**Comment by ChaeyunBae** [comment]
동의합니다!
