### ISSUE TITLE
도움! restapi로 어셋 업로드하는 기능 추가 중입니다

### ISSUE THREAD

**Issue by ChaeyunBae** [RD101/dotori#1075]
itemtype마다 파일 업로드하는 함수를 다 따로 만들어야할까요??

**Comment by ChaeyunBae** [comment]
아님 전에 얘기했던 것처럼 일단 alembic만 되게 해놓을까요?

**Comment by baesy0** [comment]
restapi함수 안에서 itemtype을 받게 되어있어서 원하는 itemtypte을 구분할 필요는 없어보여요
제가 질문의 의도를 잘 파악한게 맞나요?

**Comment by ChaeyunBae** [comment]
브라우저에서 파일을 업로드할 때는 itemtype마다 다른 함수를 실행하고 있잖아요?! handleUploadAlembicFile 나 handleUploadMayaFile 이런 식으로요
itemtype별로 switch문 돌리는 mimetype, 확장자, check data 부분들이 다르구요.
restapi로 브라우저에서 올릴 때랑 마찬가지로 itemtype 별로 함수를 다 찢어야 할지 말지 고민 중이었어요!

**Comment by baesy0** [comment]
아하 무슨 말인지 이해했어요! 정보만 넣는게 아니라 실제 데이터를 올리는 부분에 대한 거 맞죠?

**Comment by ChaeyunBae** [comment]
아아 네 맞아요!!! 그거 관련해서 pr 해보긴 했는데.... file upload 부분이 어차피 지금 작동을 안해가지고 테스트가 안돼서 일단 내렸어욬ㅋㅋㅋ!!!

**Comment by ChaeyunBae** [comment]
이건 일단 되게 만들고 나서의 문제인 것 같네요,,,,,,,,,,,,,,,,,,,,,,

**Comment by baesy0** [comment]
ㅋㅋ네! 일단 데이터가 업로드되게 만드는 이슈를 처리하고나서 또 같이 이야기해봐요!
