### ISSUE TITLE
init 페이지: 총 에셋이 20개가 안되는데 20개가 나온다고 나와요. :-)

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#1079]
<img width="707" alt="image" src="https://user-images.githubusercontent.com/1149996/89187015-9bfdae00-d5d7-11ea-9acf-cfbe7858b8c6.png">

**Comment by 78963l** [comment]
최근에 등록된 에셋만 수정되었구 merge 하면 나머지도 같은 방식으로 변경 된다구 #1074 이슈 남겼었어요
추가해서 올릴께요!
