### ISSUE TITLE
init 페이지: 태그 사이즈가 좀 더 컸으면 좋겠다.

### ISSUE THREAD

**Issue by 78963l** [RD101/dotori#1088]

**Comment by 78963l** [comment]
<img width="575" alt="스크린샷 2020-08-04 오후 2 55 21" src="https://user-images.githubusercontent.com/46780796/89258247-c2b4f680-d662-11ea-8419-ca5c601f94c6.png">

**Comment by 78963l** [comment]
이정도는 어때요?

**Comment by baesy0** [comment]
전체 페이지로 봐야 감이 잡힐 거 같아요!

**Comment by 78963l** [comment]
<img width="1676" alt="스크린샷 2020-08-04 오후 3 00 47" src="https://user-images.githubusercontent.com/46780796/89258574-60102a80-d663-11ea-845c-fb284e486393.png">

**Comment by 78963l** [comment]
<img width="1678" alt="스크린샷 2020-08-04 오후 3 02 14" src="https://user-images.githubusercontent.com/46780796/89258649-7fa75300-d663-11ea-93bc-539d7eb7f86f.png">

**Comment by baesy0** [comment]
좋아요!

**Comment by baesy0** [comment]
디자인적인 부분은 채윤님이 담당해주기로!
