### ISSUE TITLE
Storage Usage: 용량 체크 방식 변경 

### ISSUE THREAD

**Issue by ChaeyunBae** [RD101/dotori#1094]
~~현재는 dotori 서비스가 돌고 있는 서버의 전체 용량에 비해 rootpath가 차지하고 있는 용량으로 체크하고 있는데요.~~
하지만 일반적으로 어셋 저장용 스토리지를 따로 두고 서버에 마운트 시켜서 사용할 것 같아요. 
'rootpath 속 용량 / 스토리지 용량'이 돼야 맞지 않을과아요????

**Comment by khw7096** [comment]
어떻게 변경되면 좋을것 같아요? 제안부분이 빠져있어서 물어봐요.

**Comment by baesy0** [comment]
- 명령어: `df`
- USB로 테스트 해보는 방법도 있다

**Comment by 78963l** [comment]
어차피 mount 하게 되면 해당경로가 있기 때문에 그 경로를 siteRoot로 정하면 해당 디스크의 용량이 보여 수정사항이 없어도 된드아ㅎㅎㅎ

**Comment by ChaeyunBae** [comment]
- Dotori 테스트 서버에서 ```df- h``` 명령어 쳤을 때
![image](https://user-images.githubusercontent.com/46209590/89385657-e77c9d00-d73a-11ea-9014-1c1bf381d0a4.png)

- Storage Usage
![image](https://user-images.githubusercontent.com/46209590/89385728-0b3fe300-d73b-11ea-86c1-d6366d7dfc67.png)

**Comment by ChaeyunBae** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ결론 배채윤 멍청이
