### ISSUE TITLE
edit페이지에서 파일 추가 삭제 지원하기

### ISSUE THREAD

**Issue by sar9702** [RD101/dotori#1115]
데이터 파일 업로드할 때 예전 데이터 파일은 삭제해줘야 하지 않을까요?

페이지를 리로드하거나 체크데이터 페이지 갔다가 다시 업로드 페이지로 온 경우에 처음에 업로드한 파일이 아닌 새로운 데이터 파일로 업로드해서 등록한 후에 다운로드 받게 되면 두 파일 모두 받아지더라구요!

**Comment by khw7096** [comment]
동의

**Comment by khw7096** [comment]
썸네일이미지, 동영상이 빠졌을 때 안내하는 기능이 있어요.
실제 어떤상황에서 불편했는지까지 토론하면 좋을 것 같아요.

**Comment by baesy0** [comment]
썸네일 이미지만 업로드해서 체크데이터페이지에 걸렸다가 돌아오는 경우를 생각해보면, 기존의 데이터는 살아있어야 할 거 같아요.
썸네일 mov랑 data를 추가로 업로드하라고 해서 했는데 이번에는 썸네일 이미지없어..라고하면 저는.. 화가 날 거 같아요ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by baesy0** [comment]
Edit페이지에서 업로드 된 데이터들을 삭제, 추가할 수 있게 하는 건 어때요?

**Comment by sar9702** [comment]
저도 서영님 의견에 동의!
데이터 파일을 잘못 올린 경우도 처리해줘야할거같아서 edit에 데이터 파일 수정할 수 있는 기능이 필요할거같아요!

**Comment by ChaeyunBae** [comment]
저도 데이터 edit 기능 찬성!

**Comment by sar9702** [comment]
담주에 얘기해보구 제가 해볼게요!!

**Comment by baesy0** [comment]
### How to display existing files on server using DropzoneJS and go
https://hackernoon.com/how-to-display-existing-files-on-server-using-dropzonejs-and-go-53e24b57ba19

**Comment by baesy0** [comment]
<img width="980" alt="image" src="https://user-images.githubusercontent.com/40417084/91275249-d9aabc80-e7ba-11ea-8793-d12890b95e78.png">

**Comment by baesy0** [comment]
### How to show files already stored on server
https://gitlab.com/meno/dropzone/-/wikis/FAQ#how-to-show-files-already-stored-on-server

**Comment by khw7096** [comment]
이 기능이 없어도 운용상 문제가 없을 수 있다.
데이터가 바뀐다는 것은 새로운 에셋일 수 도 있기 때문에 에셋에 문제가 있다면 기존 에셋을 지우고 새롭게 등록하는 것도 하나의 방법이다.

**Comment by khw7096** [comment]
오늘 떠오른 생각은 이 기능을 지원하면,
회사에 들어온 신입이 모르고 Edit 을 하고 중요한 에셋을 지울 수 있다는 생각을 했습니다.
현재 Delete 기능은 admin 만 가능하기 때문에 보안에 안전하지만 에셋의 파일을 직접 Edit으로 지우는 건
과연 좋은 방향인지 체크할 필요가 있어보입니다.

삭제는 Admin만 하는게 어떨까요?

**Comment by ChaeyunBae** [comment]
아 이 부분 안그래도 저희끼리 얘기가 나오긴 했었는데요. 
저는 데이터 삭제는 정말 정말 신중하고 복잡한 과정을 거쳐서 해야 한다고 생각했어서 edit 페이지에서도 admin 만 delete 하게 했으면 좋겠다고 했구요.
애림님과 성민님은 데이터를 업로드한 당사자는 edit 페이지에서 삭제를 할 수 있어야 한다는 의견이었어요.
일단 저희 세 명 모두 일반 사원은 edit을 통한 data 삭제를 할 수 없게 하는 거에 대해서는 동의하고 있어요.

다들 어떻게 생각하시나요??

**Comment by khw7096** [comment]
예를 들어서 1억이 들어간 에셋이 있다고 생각했을 때 당사자라고 하더라도 이 에셋을 수정할 수 있는건~ 문제가 있어보입니다.
보통 고 부가가치의 에셋은 혼자 만들지 않거든요.

**Comment by ChaeyunBae** [comment]
지금 저희 팀 전체 회의 해봤는데요!
data edit은 admin만 가능하도록 하는 게 좋다는 결론 났어용

**Comment by khw7096** [comment]
OK!

**Comment by baesy0** [comment]
좋아요!

**Comment by baesy0** [comment]
#### 애림님이 생각하는 지점
- 버튼을 눌렀을 때 삭제되는 것이 좋을 것 같다.
- 삭제버튼을 눌렀을 때는 queueing만 되고, 버튼을 눌렀을 때 queueing된 파일이 한 번에 삭제된다.
#### 고려할 점
- 코드의 깔끔함을 높여야 한다.
- REST API를 사용하면 좋을 것 같다.

**Comment by baesy0** [comment]
#### 이 기능 자체가 필요한가
- 데이터는 삭제가 자유로우면 안된다.
- 썸네일의 경우에는 덮어쓰기가 가능하다.
- 썸네일 파일의 edit만 허용한다면 이 기능이 필요없다.

**Comment by khw7096** [comment]
이 기능도 제작되었습니다. 이 이슈를 닫습니다.
