### ISSUE TITLE
Maya / Houdini / Blender add page , section-heading 제거하기

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#113]
<img width="481" alt="image" src="https://user-images.githubusercontent.com/40417084/71346487-5f7ec400-25ab-11ea-83d1-bba4b8b262c2.png">

**Comment by baesy0** [comment]
없어도 결과에는 차이가 없다

**Comment by kybin** [comment]
왜 그럴까요?

**Comment by baesy0** [comment]
저도 그게 궁금합니다. 정확한 이유를 알면 알려주세요!

**Comment by kybin** [comment]
제가 테스트 해보니 차이가 있는데요? ㅎㅎ

**Comment by kybin** [comment]
아 저 구문을 다 지운다는 뜻이 아니군요?

**Comment by kybin** [comment]
section-heading 이라는 css 클래스가 정의되어 있지 않아서 그런거겠네요.

**Comment by baesy0** [comment]
아하! 고마워요 용빈님!:D

**Comment by khw7096** [comment]
제거해도 될듯해요~!!
