### ISSUE TITLE
CopyPath시 OS에 맞도록 복사하는 기능

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#1135]

**Comment by khw7096** [comment]
- /innerstorage
- //10.0.0.1 형태로 변경 <- admin setting에 추가되기.

**Comment by khw7096** [comment]
채윤님이 적어주세요.

**Comment by ChaeyunBae** [comment]
- Linux : /dotori/asset/5f/35/04/cb/35b213/4b43/43/b1/54/data/
- mac : /dotori/asset/5f/35/04/cb/35b213/4b43/43/b1/54/data/
- Windows : \\dotori\asset\5f\35\04\cb\35b213\4b43\43\b1\54\data\

**Comment by ChaeyunBae** [comment]
아 저희는 각 pc의  /etc/hosts 파일을 전부 바꿔주는 식으로 호스트네임들을 관리하고 있어서요! 로컬 pc마다 dotori 스토리지  ip의 hostname을 dotori로 볼수있게 설정해뒀어요

**Comment by khw7096** [comment]
넹~!
