### ISSUE TITLE
cmd: /path/test*.exr 형태 지원

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#1180]

**Comment by baesy0** [comment]
커맨드 진행하면서 테스트해보기

**Comment by khw7096** [comment]
- 레귤러 익스프레션을 이용하는 방법
- * 문자로 스플릿하고 header, tail을 비교하는 방법

**Comment by khw7096** [comment]
와일드 카드 매칭이 이미 있음.

https://godoc.org/github.com/minio/minio/pkg/wildcard

**Comment by khw7096** [comment]
- footage 로 테스트하기 좋다.
- 표준라이브러리(glob)와 가독성(pkg/wildcard) 중에는 표준라이브러리를 더 추천한다.

**Comment by khw7096** [comment]
cmd api, footage로 테스트할 것

**Comment by baesy0** [comment]
### wildcard 라이브러리 레포지터리

https://github.com/minio/minio/tree/36d36fab0bfeb0e91099e852408d0e1ac2e06440/pkg/wildcard
