### ISSUE TITLE
RestAPI : 삭제 경로가 존재하지 않으면 삭제 실패 에러메시지가 뜬다.

### ISSUE THREAD

**Issue by ChaeyunBae** [RD101/dotori#1200]
![image](https://user-images.githubusercontent.com/46209590/90842580-9f948180-e39a-11ea-83bd-9e6c1006a3fc.png)

data는 없고 db에만 쌓여있을 경우에는 delete를 못하는데 이건 무조건 cleanup db로 지워야할까요?
아니면 delete 하는 함수를 조금 더 보완할까요? 전 보완하는 거에 한 표!

**Comment by baesy0** [comment]
저도 보완에 한 표!

**Comment by khw7096** [comment]
경로가 존재하면 그때만 삭제하도록 변경하기 isExist()
