### ISSUE TITLE
명칭바꾸기. 로고를 변경했으면 좋겠다. - RD101 측

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#124]

**Comment by khw7096** [comment]
저는 찬성해요.

**Comment by khw7096** [comment]
openpipeline.io 수정,  foundry Korea 문서 수정

**Comment by baesy0** [comment]
기본 로고 넣기.

**Comment by khw7096** [comment]
https://vectr.com/bailey0/adpMyZFva.svg?width=368&height=368&select=adpMyZFvapage0

에러를 없애기 위해서 위 로고를 먼저사용. svg 작업까지 되어있다.
