### ISSUE TITLE
hdri 페이지 디자인

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#1248]
- 업로드 버튼 위치, 크기

**Comment by baesy0** [comment]
<img width="347" alt="image" src="https://user-images.githubusercontent.com/40417084/91943640-e342a000-ed37-11ea-9001-8abb2cd6c286.png">

**Comment by baesy0** [comment]
<img width="239" alt="image" src="https://user-images.githubusercontent.com/40417084/91943715-fd7c7e00-ed37-11ea-89e9-147d3a69ba17.png">

**Comment by baesy0** [comment]
- 아직 버튼 활성/비활성화 기능같은건 안붙였어요
- 버튼 크기를 약간 줄이고
- 드롭존의 우하단에 배치해보았어요.

의견이 있으면 알려주세요!

**Comment by khw7096** [comment]
제안

<img width="774" alt="image" src="https://user-images.githubusercontent.com/1149996/92226680-1031b700-eee0-11ea-8e09-ea28a6768f93.png">
