### ISSUE TITLE
자잘한 디자인 수정

### ISSUE THREAD

**Issue by ChaeyunBae** [RD101/dotori#1257]
- [x] : items.css > default.css로 합치기
- [x] : 최초 안내 페이지 tags 모양 변경
- [x] : 최초 안내 페이지 아이패드, 핸드폰 화면일 때 card 끼리 안겹치게 수정
- [x] : detailview ajax 실패 했을 때 모달창 안뜨게 하기
- [x] : detailview 모달창 핸드폰 화면일 때 왼쪽으로 붙는 버그 수정
- [ ] : item이 video일 때 card 위에 공간 생기는 거 없애기(adminsetting에서 가져오는 거랑 관련 있음)
- [x] : 삭제 모달 창 가로 길이 줄이기
- [x] : 최초 안내페이지 줄 간격 수정

**Comment by ChaeyunBae** [comment]
dotori 테스트 해보다가 거슬리는 애들 여기에 기록해두고 있어요!! 다른 분들도 보면 알려주세요!

**Comment by baesy0** [comment]
> dotori 테스트 해보다가 신경쓰이는 애들 여기에 기록해두고 있어요!! 다른 분들도 보면 알려주세요!

넹넹!
