### ISSUE TITLE
commandline으로 에셋을 추가할 때 tag가 1개만 들어간다. 문제점을 더블체크하기.

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#127]

**Comment by sar9702** [comment]
여러가지 형태로 태그를 입력해봤는데 잘 안되네요ㅠㅠ
제가 옵션을 잘못 주고 있는건가요...?

```bash
$ dotori -add -author bae -type nuke -inputpath /library/asset -outputpath /library/asset -tag "fire,fx"
```
![1](https://user-images.githubusercontent.com/14924389/72040878-4ab16880-32ed-11ea-8ebe-1c697d6174ee.png)

```bash
$ dotori -add -author bae -type nuke -inputpath /library/asset -outputpath /library/asset -tag fire -tag fx
```
![2](https://user-images.githubusercontent.com/14924389/72040953-83e9d880-32ed-11ea-9836-1afaea5a93c1.png)

```bash
$ dotori -add -author bae -type nuke -inputpath /library/asset -outputpath /library/asset -tag "fire","fx"
```
![3](https://user-images.githubusercontent.com/14924389/72041008-ada2ff80-32ed-11ea-931c-7edf1a15c704.png)

```bash
$ dotori -add -author bae -type nuke -inputpath /library/asset -outputpath /library/asset -tag "fire" "fx"
```
![4](https://user-images.githubusercontent.com/14924389/72041077-e8a53300-32ed-11ea-8e4d-9c56f157bc47.png)

**Comment by khw7096** [comment]
-tag "fire,fx"

형태로 주는 게 맞을 듯해요. -tag은 아귀먼트이고 value로 문자열이 들어가야 하니까요.

**Comment by sar9702** [comment]
태그에서 앞 뒤 공백을 제거하고 띄어쓰기로 split해서 리스트를 리턴해주는 함수를 작성하려고 하는데
그 함수는 어느 파일에 추가하는 게 좋을까요?

**Comment by khw7096** [comment]
애림님의 의견에 대해서...

함수를 만든다면 stringsfunc.go 는 어때요?

**Comment by baesy0** [comment]
stringsfunc.go는 문자열 처리를 하는 함수를 모아두려는 건가요?

**Comment by khw7096** [comment]
네 앞으로 많아질 것 같아서요.

**Comment by sar9702** [comment]
네네 좋아요!!
