### ISSUE TITLE
dropzone: 삭제하기 전에 확인 문구 뜨는 옵션

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#1276]
<img width="598" alt="image" src="https://user-images.githubusercontent.com/40417084/92320539-25802000-f05d-11ea-83b1-daaa8a6e3773.png">

삭제되기 전에 확인창이 뜨는 건 어떠냐는 의견이 나왔던 것 같아서
관련 옵션을 공유해두어요!

**Comment by baesy0** [comment]
### 사용 예
null 대신 문구를 입력하면, 삭제버튼을 눌렀을 때 해당 문구가 뜹니다
<img width="601" alt="image" src="https://user-images.githubusercontent.com/40417084/92321344-24062600-f064-11ea-966d-9f7156b6829e.png">


<img width="515" alt="image" src="https://user-images.githubusercontent.com/40417084/92321335-15b80a00-f064-11ea-9173-061866e01403.png">

**Comment by khw7096** [comment]
오~~ 이거쓰면 확실히 편리할 듯 하네용.

**Comment by baesy0** [comment]
공유된듯하니 일단 닫겠습니다!
