### ISSUE TITLE
clip의 경우 썸네일 이미지가 나오지 않음.

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#1278]
![image](https://user-images.githubusercontent.com/1149996/92325890-f089c280-f088-11ea-9825-6acf9d94a43a.png)

![image](https://user-images.githubusercontent.com/1149996/92328552-93980780-f09c-11ea-8767-af5370dd6d11.png)

썸네일 이미지가 존재하지 않을 때 썸네일 이미지 옵션을 설정하면 안된다.

**Comment by ChaeyunBae** [comment]
![image](https://user-images.githubusercontent.com/46209590/92341096-a986e600-f0f7-11ea-9e4f-b360c83be1f1.png)
지금 http_clip.go에는 .png나 .jpg를 썸네일로 처리하는 부분이 없어서 항상 이런 식으로 썸네일이 없다고 뜨네요. http_clip.go도 수정하는 게 좋을까요? 아니면 hdri 처럼 썸네일 이미지를 자동으로 생성해주는 부분을 추가해야할까요??
