### ISSUE TITLE
이부분은 itemtype, type이 코드에서 혼용되고 있다. 통일하기.

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#128]
https://github.com/RD101/dotori/blob/137595d131a57018ae86b4663b3a55dfca344d4e/http.go#L68

**Comment by baesy0** [comment]
- http_restapi.go
- http.go
- testdata.sh
에서 쓰이고 있음

**Comment by khw7096** [comment]
go에서 type은 예약어예요. itemType 또는 itemtype을 추천해요.

**Comment by sar9702** [comment]
변수들도 itemType을 사용하는데 itemType으로 통일할까요?

**Comment by khw7096** [comment]
네~
