### ISSUE TITLE
design 개선

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#1286]
<img width="856" alt="image" src="https://user-images.githubusercontent.com/1149996/92353816-0d230a80-f11c-11ea-8b2e-62f3d61e6a92.png">

in-line이 맞으면 시각적으로 좋을 것 같아요. 지금 레이아웃은 일반적인 디자이너가 사용하는 느낌은 아니예요.

**Comment by ChaeyunBae** [comment]
이거 제가 한번 해볼게요. 저도 이렇게 하고 싶었는데 수정이 좀 크게 들어가야 할 것 같아서 일단 나두고 있었거든요! init 페이지의 전체적인 html 그룹 구조가 바뀔 수도 있을 것 같아요

**Comment by ChaeyunBae** [comment]
어렵네요... 도움...
