### ISSUE TITLE
최초 안내 페이지: 에셋이 2개일 때 레이아웃이 어색하다

### ISSUE THREAD

**Issue by dchecheb** [RD101/dotori#1293]
![image](https://user-images.githubusercontent.com/46209590/93041174-dbafbf00-f686-11ea-8a18-52dfbdb3eb56.png)
두둥 충격과 공포

**Comment by khw7096** [comment]
두개만 어색한가요?

**Comment by ChaeyunBae** [comment]
넵 맞아요 초기 한 순간이긴 한데.. 신경쓰기이긴 해요
제가 item에 `justify-content: space-between;` 속성 넣어서 생긴 문제인데... 2개일 땐 저렇게 양쪽 끝으로 붙어버려요
그래서 일단 무조건 4개 카드 깔고 hidden? 을 하는 방법으로 바꿔야 하나 생각 중이었어요!

**Comment by khw7096** [comment]
만약 신경쓰인다면, 2개일때는 페이지 필요없고 좌측정렬이 되는게 좋아보일듯합니다.

**Comment by baesy0** [comment]
ㅋㅋㅋㅋㅋ두둥

**Comment by khw7096** [comment]
성민님이 봐주기로 했다.

**Comment by ChaeyunBae** [comment]
아싸뵤

**Comment by 78963l** [comment]
흠.. 이걸어떻게 바꿔야할까요? ㅎㅎ

**Comment by baesy0** [comment]
왼쪽 정렬되게 하는 건 어때요?
