### ISSUE TITLE
edit 성공 페이지 다음에 search 페이지로 연결돼서 빈 화면이 뜬다

### ISSUE THREAD

**Issue by ChaeyunBae** [RD101/dotori#1300]

**Comment by khw7096** [comment]
수정한 에셋의 페이지로 이동하면 좀더 편리하다.

**Comment by khw7096** [comment]
HOME 대신 이전으로 돌아가기 라고 바꾸고 이동을 javascript 로 간단하게 구현하는것이 더 좋을 것 같다.

**Comment by ChaeyunBae** [comment]
이전으로 돌아가기라고 바꾸는 거면 그냥 자바스크립트로 뒤로 가기하는 건가요??
