### ISSUE TITLE
Upload Files 버튼이 전 타입에 적용되도록 하기.

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#1310]

**Comment by baesy0** [comment]
1. add*아이템타입*-file.html
    - dropzone id 수정 : *아이템타입*Dropzone
    - UploadFiles 버튼 추가
    - 등록버튼 수정

**Comment by baesy0** [comment]
- [ ] Maya
- [ ] nuke
- [ ] houdini
- [ ] blender
- [ ] alembic
- [ ] USD
- [ ] openVDB
- [ ] modo
- [ ] katana
- [ ] fusion360
- [ ] max
- [ ] lut
- [ ] unreal
- [ ] sound
- [ ] hwp
- [ ] pdf
- [ ] ppt
- [ ] texture
- [ ] ies
- [ ] hdri
- [ ] clip
- [ ] footage
