### ISSUE TITLE
struct User에서  AccessLevel이 필요한가요??

### ISSUE THREAD

**Issue by 78963l** [RD101/dotori#1333]
struct Token에서 AccessLevel를 가져오는 부분이랑 struct User에서 AccessLevel가져오는 부분을 혼용하여 사용합니다.

예를 들어 struct User의 AccessLevel를 admin으로 바꿨을 때 profile에서의 변동과 delete버튼이 보이는 부분이고,

delete버튼을 눌렀을때에는 token의 AccessLevel에서 가져와 비교하여 delete가 적용되지 않는 부분입니다.

결론은 struct User에 AccessLevel을 왜 추가했는지가 궁금합니다!

**Comment by khw7096** [comment]
Token에 선언한 AccessLevel은 DB에 접근안하고 AccessLevel을 가지고 올 수 있어서 웹페이지에서 효율적이라서 최대한 Token의 AccessLevel을 가지고 오는것을 추천해요. 대신 AccessLevel이 바뀌면 Token도 변경되어야 하겠지요.

**Comment by 78963l** [comment]
답변감사합니다!
