### ISSUE TITLE
질문 ! dotori에 소스용 시퀀스들을 저장해두려고 하는데 itemtype을 뭐로 설정해야할지 모르겠어요

### ISSUE THREAD

**Issue by dchecheb** [RD101/dotori#1353]
저희 스토리지 안에 아래처럼 저장돼있는 소스들을 도토리에 업로드하려고 해요.
```bash
fire
├── fire.1001.jpg
├── fire.1002.jpg
├── fire.1003.jpg
└── fire.mov
```
clip에 jpg 파일 포맷도 가능하게 추가해야하는 건지, 아니면 source용 아이템 타입 자체를 추가해야할지 헷갈려요 어떻게 하면 좋을까요?

**Comment by joonkyun** [comment]
현재 footage 항목에 
exr 시퀀스 업로드가 되지 않습니다.
이 항목에 exr 확장자를 허용하지 않는 특별한 이유가 있는지 궁금합니다.

**Comment by baesy0** [comment]
> 저희 스토리지 안에 아래처럼 저장돼있는 소스들을 도토리에 업로드하려고 해요.
> 
> ```shell
> fire
> ├── fire.1001.jpg
> ├── fire.1002.jpg
> ├── fire.1003.jpg
> └── fire.mov
> ```
> 
> clip에 jpg 파일 포맷도 가능하게 추가해야하는 건지, 아니면 source용 아이템 타입 자체를 추가해야할지 헷갈려요 어떻게 하면 좋을까요?

이건 같이 이야기해봐야 할 것 같아요!
현재 clip은 동영상포맷만 업로드되도록 되어있고
Footage의 경우 jpg를 허용하고 있지 않아서
위의 경우를 처리해주는 기능이 없어요.
새로 이슈를 만들어서 토론해봐요!

**Comment by baesy0** [comment]
> 현재 footage 항목에
> exr 시퀀스 업로드가 되지 않습니다.
> 이 항목에 exr 확장자를 허용하지 않는 특별한 이유가 있는지 궁금합니다.

확인해본 결과 exr은 허용하는 포맷인데 왜 업로드되지 않는지는 체크해봐야할 것 같아요.
혹시 에러메세지 뜬 게 있다면 공유해주시겠어요?

**Comment by joonkyun** [comment]
![dotori_footage_add_01](https://user-images.githubusercontent.com/30970772/99748775-7feb3180-2b20-11eb-9e1b-902d44ab21c2.png)
![dotori_footage_add_02](https://user-images.githubusercontent.com/30970772/99748781-824d8b80-2b20-11eb-8d54-10046c002199.png)

**Comment by baesy0** [comment]
토론되고 있는 주제가 두 개니까 일단 각 주제에 대해서 새로운 이슈를 만들게요!
