### ISSUE TITLE
검색창 콤보박스 메뉴 선택시

### ISSUE THREAD

**Issue by joonkyun** [RD101/dotori#1354]
아래 그림과 같이 콤보박스에서 항목을 선택하고 search 를 누르면 아무것도 안보입니다.
모든 것을 보려면 all 이란 키워드로 검색을 해야 하는데
사용자 입장에선 좀 불편해 보입니다. 
메뉴 선택시 기본 all이란 키워드로 자동 검색되어 결과를 보여주는 방식은 어떨까요?
메뉴 선택시 자동이 어렵고 좋지 않은 방식이라면 아무런 키워드도 주어주지 않고
빈칸일때 search 버튼을 클릭하면 all 키워드로 검색하는 것과 같은 효과를 주는 것은 어떨까요?

![Screenshot from 2020-11-19 11-27-54](https://user-images.githubusercontent.com/30970772/99613455-edcd2580-2a5a-11eb-994d-edcb0c72aee6.png)

**Comment by baesy0** [comment]
(팀장님 깃허브에서 만나니까 반갑네요:D)
- 자동으로 all 검색 결과를 띄우지 않은 이유
전체 샷이 검색된 페이지를 디폴트로 설정해놓으면 DB서버에 큰 부하를 주게 돼요
“DOTORI 사용자 수 * 메인 페이지 접근 횟수 * 전체 아이템 수” 만큼의 쿼리를 매번 DB서버에 보내게 되어서요.

- 빈칸으로 검색시 all로 검색한 것과 같은 효과내는 것
좋은 대안인 거 같아요!
위와 같은 이유가 있다지만 그래도 편리함과는 거리가 있었는데, 좋은 중간 지점인 것 같아요:)

**Comment by joonkyun** [comment]
감사합니다.

**Comment by baesy0** [comment]
다른 분들도 동의한다면 이슈를 만들어서 진행할게요!

**Comment by dchecheb** [comment]
빈 칸 동의합니다~!

**Comment by baesy0** [comment]
이슈를 생성했으니 토론을 위한 이슈는 닫을게요!
