### ISSUE TITLE
jpg형태의 소스를 어떻게 처리할 것인가

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#1355]
저희 스토리지 안에 아래처럼 저장돼있는 소스들을 도토리에 업로드하려고 해요.
```bash
fire
├── fire.1001.jpg
├── fire.1002.jpg
├── fire.1003.jpg
└── fire.mov
```
clip에 jpg 파일 포맷도 가능하게 추가해야하는 건지, 아니면 source용 아이템 타입 자체를 추가해야할지 헷갈려요 어떻게 하면 좋을까요?

_Originally posted by @dchecheb  in https://github.com/RD101/dotori/issues/1353#issuecomment-730798909_

**Comment by baesy0** [comment]
1. clip vs footage 중 어느 곳이 더 적합한가.
clip은 단순한 영상을 올리는 곳이니까 footage가 맞을 거 같아요.

2. footage에 올린다면
2-1. jpg파일은 알파값이 없는 포맷이어서 소스로서 가치가 있는지 궁금해요.
2-2. mov파일이 왜 있는지 궁금해요. footage에서 연산시 자동으로 썸네일 영상을 만들어주고 있어서요.

**Comment by khw7096** [comment]
jpg는 프록시이기는 하지만 확률상 소스로서 가치가 있을 수 있다고 판단해요. footage를 통해서 올릴 수 있도록 지원하는 것이 좋을 것 같아요.

**Comment by dchecheb** [comment]
이게.. 기존에 소스 보관용 스토리지에 있는 것들을 전부 도토리에 올리려고 하다가 생긴 이슈인데요.
아무래도 정리가 제대로 안돼있는 폴더도 있다보니 한 소스 폴더 안에 여러 가지 확장자가 섞여있는 경우도 있어서 문제가 됐어요. 저 fire 폴더처럼요.

확인해보니까 .mov 파일들은 썸네일용 파일이라 제외해도 될 것 같은데요. `.dpx`, `.png`, `.jpg` 도 footage에 올릴 수 있으면 좋을 것 같습니다.

**Comment by dchecheb** [comment]
같은 폴더에 여러 확장자 파일들이 섞여 있는 경우에는 따로 올리는 게 맞겠죠?

**Comment by dchecheb** [comment]
그리고 저희가 업로드 하려는 게 촬영본이 아니라 소스라서 fps, colorspace 등등의 정보는 사실 필요 없거든요! 제 생각에는 source용 itemtype을 추가하는 게 좋을 것 같은데 어떻게 생각하세요??

**Comment by baesy0** [comment]
footage 타입에서 허용하는 확장자를 추가하기 보다는
source 타입을 새로 만드는 게 좋을 것 같다는 걸로 이해했는데 맞을까요?

**Comment by dchecheb** [comment]
넵 맞아요 clip은 mp4같은 영상에 적합한 itemtype 이고, footage는 촬영본에 적합한 itemtype인 것 같다는 생각이 들어서요. footage를 등록할 때 필수로 입력해야하는 color space와 fps, 장소 등등은 제가 올리고자 하는 source asset에서 필요없는 정보들이에요!

**Comment by khw7096** [comment]
저는 source라는 이름을 사용하는 것에 대해서 약간은 반대하는 입장입니다.
우리가 저장하는 모든 에셋은 사실상 source인데, 그 안에 source type이 생기면 의미상 이상해 보일 것 같아요.
개인적으로 jpg 시퀀스라면 footage가 더 좋아보인다고 생각하고 태그에 8bit 같은 비트 정보를 넣는것도 방법이라고 생각합니다.

**Comment by baesy0** [comment]
저는 새로운 아이템타입이 필요하다면 추가하는 것에는 찬성이에요.
다만 해당 아이템타입에 대해 구체적이고 명확한 정의가 있으면 좋겠어요.
source 타입은 아직 추상적인 느낌이 들어요.
그 안에 넣을 에셋은 어떤 에셋인지 명확한 정의가 먼저 필요할 것 같아요.

**Comment by dchecheb** [comment]
맞는 말씀인 것 같아요!  어쨋든 저희가 올리고자 하는 asset들은 footage라는 범위에 속하기 때문에 footage에 올리는 게 맞다고 생각으로 바뀌었어요. 
그런데 저희 쪽에서 문제는 올리고자 하는 시퀀스들의 fps, color space를 모른다는 거예요ㅠㅠㅠ!  footage에 올리고 fps, color space는 임의로 지정해서 업로드해야할 것 같네요.

**Comment by dchecheb** [comment]
> 저는 source라는 이름을 사용하는 것에 대해서 약간은 반대하는 입장입니다.
> 
> 우리가 저장하는 모든 에셋은 사실상 source인데, 그 안에 source type이 생기면 의미상 이상해 보일 것 같아요.
> 
> 개인적으로 jpg 시퀀스라면 footage가 더 좋아보인다고 생각하고 태그에 8bit 같은 비트 정보를 넣는것도 방법이라고 생각합니다.

맞는 말씀인 것 같아요!  어쨋든 저희가 올리고자 하는 asset들은 footage라는 범위에 속하기 때문에 footage에 올리는 게 맞다고 생각으로 바뀌었어요. 
그런데 저희 쪽에서 문제는 올리고자 하는 시퀀스들의 fps, color space를 모른다는 거예요ㅠㅠㅠ!  footage에 올리고 모르는 옵션들은 임의로 지정해서 업로드해야할 것 같네요.

**Comment by dchecheb** [comment]
> 저는 새로운 아이템타입이 필요하다면 추가하는 것에는 찬성이에요.
> 
> 다만 해당 아이템타입에 대해 구체적이고 명확한 정의가 있을 때 하는 게 좋을 것 같아요.
> 
> source 타입은 아직 추상적인 느낌이 들어요.
> 
> 그 안에 넣을 에셋은 어떤 에셋인지 명확한 정의가 먼저 필요할 것 같아요.

이 댓글을 이제 봤네요..

**Comment by khw7096** [comment]
컬러스페이스를 모를 땐, sRGB to sRGB 로 처리하면 되요.

**Comment by dchecheb** [comment]
감사합니다~!
