### ISSUE TITLE
footage 타입 파일 업로드 시 exr파일이 업로드 되지 않는 문제

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#1356]
![dotori_footage_add_01](https://user-images.githubusercontent.com/30970772/99748775-7feb3180-2b20-11eb-9e1b-902d44ab21c2.png)
![dotori_footage_add_02](https://user-images.githubusercontent.com/30970772/99748781-824d8b80-2b20-11eb-8d54-10046c002199.png)

이상태에서 업로드도 되지 않고 아무것도 안되네요.

_Originally posted by @joonkyun in https://github.com/RD101/dotori/issues/1353#issuecomment-730798909_

**Comment by khw7096** [comment]
<img width="491" alt="image" src="https://user-images.githubusercontent.com/1149996/99791321-cbc1c900-2b68-11eb-8f93-49521fd7cb98.png">

위 버전에서 잘 올라가고 있습니다. 버전 더블체크 및 상황에 따른 다른 버그가 있을 것 같습니다.

**Comment by khw7096** [comment]
혹시 최신 도토리로 해보고 안된다면 안되는 브라우저와 OS환경을 적어주면 다른 환경을 만났을 때 도움될 것 같습니다.

**Comment by dchecheb** [comment]
저희는 release 버전 말고 clone 받아서 컴파일한 파일로 서비스 돌리고 있어요! 그래서 현재 github 코드 상에 있는 가장 최신버전이에요

**Comment by dchecheb** [comment]
브라우저는 크롬이었고 OS는 centos7.4였다고 하십니다!

**Comment by khw7096** [comment]
크롬 버전은 어떻게 되나요?

구글에서 해당 이슈로 검색 했을 때 크롬 버전 정보, CentOS7.4가 출시된 연도도 중요할 듯해요.

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/1149996/100322590-d9170180-3007-11eb-8964-094db1d5ed97.png">

**Comment by khw7096** [comment]
![image](https://user-images.githubusercontent.com/1149996/100322947-53e01c80-3008-11eb-9132-c6402690d202.png)

https://en.wikipedia.org/wiki/CentOS#CentOS_version_7

**Comment by khw7096** [comment]
혹시 파이어폭스는 어떤지도 체크해봐주실 수 있나요?

**Comment by dchecheb** [comment]
지금 제 노트북에선 되는데 회사 컴퓨터에선 안되는 것 확인했었어요! 회사 컴퓨터는 크롬 버전이 낮았었던 거로 기억해서 월요일에 확인해보고 여기 기록해둘게요! 
mimetype 어떻게 찍히는지도 월요일에 확인해보겠습니다

**Comment by dchecheb** [comment]
## Chrome
- 버전 : Version 72.0.3626.109 
- exr의 mimetype : `image/x-exr`
- 허용하지 않는 포맷 에러 발생

## Firefox
- 버전 : 52.2.0
- exr의 mimetype : `application/octet-stream`
- 아래와 같은 에러가 뜨면서 프로세스 실패
```bash
[/blank/5f/c4/48/69/389116/6c06/27/9d/5f/data//checkbox.exr --colorconvert linear linear --fit 320x180 -o /blank/5f/c4/48/69/389116/6c06/27/9d/5f/thumbnail/thumbnail.png]
경로가 시퀀스 형식이 아닙니다
```

**Comment by khw7096** [comment]
checkbox.exr 은 당연히 시퀀스가 아닌.. 그냥 이미지 파일 소스 아닌가요? footage는 시퀀스로 테스트 해봐야할 듯해요.

허용하는 type에 image/x-exr을 추가하면 좋을 것 같아요.

**Comment by dchecheb** [comment]
아 저희 스토리지에  test.0123.123122.exr 이런 파일들도 있는데 이것도 안되더라구요! 그 부분 레귤러 익스프레션으로 어떻게 처리 할지 테스트해보고 있었어요! 저거슨 잘못썼네요

**Comment by dchecheb** [comment]
노트북에선 또 되네요...

**Comment by joonkyun** [comment]
![chrom_ver](https://user-images.githubusercontent.com/30970772/100686461-b9922700-33c1-11eb-9a2c-b20fb5c85dbf.png)
현재 크롬을 위 버전으로 업데이트 했는데도 같은 에러가 나네요

**Comment by baesy0** [comment]
크롬의 경우는 mimetype을 추가해주고 다시 테스트해보면 될 것 같아요!
firefox

> 아 저건 제가 잘못 올렸네요ㅠㅠ 그런데 스토리지에 test_001.000688.exr 이런 파일들도 있는데 이것도 안되더라구요!
> 에러메시지는 안찍히고
> ![image](https://user-images.githubusercontent.com/46209590/100582244-49859180-332c-11eb-93a1-c027382f6bd2.png)
> 이런 에러가 떠요!

https://stackoverflow.com/questions/14885748/ssh-script-returns-255-error
255에러라면 코드 문제는 아닌 것 같아요. RD101쪽에서 확인해봐야 할 것 같아요:)
- 서버가 다운되어 있는지
- 서버에 ssh가 깔려있는지
- ffmpeg가 깔려있는지
- OCIO가 깔려있는지
- OIIO가 깔려있는지
- admin setting에서 ffmpeg 경로가 잘 연결되어 있는지
- admin setting에서 OCIO 경로가 잘 연결되어 있는지
- admin setting에서 OIIO 경로가 잘 연결되어 있는지
이런 거 체크해봐야 할 것 같아요.

**Comment by baesy0** [comment]
> ![chrom_ver](https://user-images.githubusercontent.com/30970772/100686461-b9922700-33c1-11eb-9a2c-b20fb5c85dbf.png)
> 현재 크롬을 위 버전으로 업데이트 했는데도 같은 에러가 나네요

크롬의 경우는 mimetype을 추가해주고 다시 테스트해보면 될 것 같아요!

**Comment by dchecheb** [comment]
> > 아 저건 제가 잘못 올렸네요ㅠㅠ 그런데 스토리지에 test_001.000688.exr 이런 파일들도 있는데 이것도 안되더라구요!
> > 에러메시지는 안찍히고
> > ![image](https://user-images.githubusercontent.com/46209590/100582244-49859180-332c-11eb-93a1-c027382f6bd2.png)
> > 이런 에러가 떠요!
> 
> https://stackoverflow.com/questions/14885748/ssh-script-returns-255-error
> 255에러라면 코드 문제는 아닌 것 같아요. RD101쪽에서 확인해봐야 할 것 같아요:)
> 
> * 서버가 다운되어 있는지
> * 서버에 ssh가 깔려있는지
> * ffmpeg가 깔려있는지
> * OCIO가 깔려있는지
> * OIIO가 깔려있는지
> * admin setting에서 ffmpeg 경로가 잘 연결되어 있는지
> * admin setting에서 OCIO 경로가 잘 연결되어 있는지
> * admin setting에서 OIIO 경로가 잘 연결되어 있는지
>   이런 거 체크해봐야 할 것 같아요.

ssh, ffmpeg, ocio, oiio 등은 작동하고 있긴 해서 command 똑같이 쳐서 테스트해볼게요! 감사합니다! :D

**Comment by dchecheb** [comment]
혹시 csi.lazypic.org:8089에서 돌고있는 도토리는 oiio 몇 버전 사용하시나요?!

**Comment by khw7096** [comment]
![image](https://user-images.githubusercontent.com/1149996/101246920-aa143480-3759-11eb-824f-b630c769d653.png)

버전은 2.1.17 입니다.

**Comment by dchecheb** [comment]
감사합니다! 
저희는 1.5.24 였어서 안됐던 것 같아요 oiio 높은 버전으로 다시 빌드 뜨고 커맨드 실행하니까 잘 되네요! 예!!!!!!!

**Comment by dchecheb** [comment]
## 에러 처리 과정

### 1. exr -> png 컨버팅 에러 확인
저희 Linux 서버(CentOS 7.4) 에 OIIO는 yum을 이용해서 설치했었는데요. 비교적 낮은 버전인 1.5.24 버전이 받을 수 있는 가장 최신 버전이었어요. 그런데 특정 .exr 파일은 png로 컨버팅이 안되는 문제가 있었어요! 
```bash
$ oiiotool /blar/blar_blar.1005.exr --colorconvert linear linear --fit 320x180 /blar/blar_blar.1005.png
oiiotool ERROR: read : OpenImageIO could not open "/blar/blar_blar.1005.exr" as exr: OpenEXR exception: Cannot read image file "/blar/blar_blar.1005.exr". Unknown compression type in image header.
```
- converting 되는 exr의 metadata
![image](https://user-images.githubusercontent.com/46209590/101313847-915f6800-389a-11eb-8899-a9175daf5f20.png)
- converting 안되는 exr의 metadata
![image](https://user-images.githubusercontent.com/46209590/101313885-aa681900-389a-11eb-8b20-bc74784bc0a0.png)

### 2. OpenImageIO 버전 업그레이드
잘 작동되는 서버(macOS는 brew install로 깔면 자동으로 oiio2 이상 버전이 깔렸음)에서 OIIO 버전이 더 높은 것을 보고
OpenImageIO 를 업그레이드 했습니다. github에 release 된 버전 다운 받아서 빌드했더니 변환 성공했습니다 :D

**Comment by khw7096** [comment]
DWAA 압축 방식은 최근에 나온 방식이라서 에러가 났나보군요.

**Comment by baesy0** [comment]
멋져.. ❤️
해결과정 정리해둔 것도, 해결한 것도 다 멋져..

**Comment by dchecheb** [comment]
얏호 감사합니다~~!~! ❤️
