### ISSUE TITLE
Footage : premultiply 적용 여부 체크박스 추가(ffmpeg로 png 시퀀스 -> video 변환 시)

### ISSUE THREAD

**Issue by dchecheb** [RD101/dotori#1366]
## png 썸네일
![image](https://user-images.githubusercontent.com/46209590/101589966-d7e4cc00-3a2c-11eb-881c-bd7ad0b5b1a8.png)

## video 썸네일
![image](https://user-images.githubusercontent.com/46209590/101589933-bf74b180-3a2c-11eb-981b-b7d65fb9d968.png)

exr 파일을 올렸을 때 썸네일용 위 png 그림처럼 뒤 배경이 투명하게 들어오는 게 정상인데요! video를 플레이하면 위 사진처럼 뒤 배경 색이 이상하게 변하더라구요. 같은 png 파일이지만 뒤 배경으로 검정색이 들어왔느냐 안들어왔느냐의 차이인 것 같은데.. 해결 방법을 못찾고 있어요!

ffmpeg로 png 시퀀스를 video로 변환할 때의 옵션 자체에 premultiply 적용을 해야하는 걸지, adminsetting의 video 코덱을 변경하는 거로 해결이 가능한 건지 잘 모르겠어서 질문드립니다ㅠㅠ!

**Comment by dchecheb** [comment]
그리고 한 가지 더 궁금한 점이 있어요! 아마 설명주셨었던 내용 같긴한데 썸네일 이미지와 proxy 시퀀스를 png로 뽑았던 이유가 있었나요??

**Comment by dchecheb** [comment]
엇 원인이  png -> mp4 부분 문제가 아닌 것 같아요 조금 더 테스트해보고 다시 열게요!

**Comment by khw7096** [comment]
일반저긍로 premultiply가 적용되지 않아요. 한다면 옵션을 찾아서 premultiply 해야할 듯해요. 당연히 premultiply 하겠다는 옵션도 웹 UX에 추가되어야겠어요.

**Comment by khw7096** [comment]
png가 영상제작시 jpg보다 퀄리티가 좋기때문에 사용했습니다.

**Comment by dchecheb** [comment]
넵 감사합니다! 제가 한번 해보고 안되겠으면 도움 요청 드릴게요!!

**Comment by dchecheb** [comment]
## exec command 출력,에러 받아오기
```go
	cmd := exec.Command(adminSetting.FFmpeg, args...)
	var outb, errb bytes.Buffer
	cmd.Stdout = &outb
	cmd.Stderr = &errb
	err = cmd.Run()
	log.Println("out: ", outb.String())
	log.Println("err: ", errb.String())
```

**Comment by khw7096** [comment]
해결 방법이 좋아보여요~
