### ISSUE TITLE
Process: LD_LIBRARY_PATH 환경변수 세팅하기

### ISSUE THREAD

**Issue by dchecheb** [RD101/dotori#1370]
adminsetting에서 `LD_LIBRARY_PATH`를 설정해놔도 library들을 못 땡겨와서 봤더니 
library path 세팅하는 코드부가 없더라구요.

~~`exec.Command(args)`로 명령어 실행하기 전에는 항상~~ `processingItem`에서  `LD_LIBRARY_PATH` 환경변수 세팅하게끔 추가 예정입니다.

**Comment by dchecheb** [comment]
- os에 한 번 세팅해주면 모든 프로세스에서 해당 값을 참조하기 때문에 매번 세팅해줄 필요는 없음.
- web 서버 실행할 때, adminsetting update 할 때만 환경변수 세팅해주면 될듯

**Comment by khw7096** [comment]
당시에 예비로 만들어두었던 옵션이예요. 이제 쓸일이 생겼나요?
