### ISSUE TITLE
즐겨찾기: 아이템 Delete 할 때 즐겨찾기에서도 삭제해주기

### ISSUE THREAD

**Issue by dchecheb** [RD101/dotori#1373]
즐겨찾기에 등록했던 item이 삭제되면 favoriteassets 페이지에서 에러 발생함

![image](https://user-images.githubusercontent.com/46209590/102601669-d40b2500-4163-11eb-8fcb-54c858a8e361.png)

**Comment by khw7096** [comment]
버그가 있었군요.
