### ISSUE TITLE
Process: jobs 채널에 item이 중복으로 쌓이는 버그

### ISSUE THREAD

**Issue by dchecheb** [RD101/dotori#1380]
processingItem이  item이 jobs 채널에 들어간지 10초 후에도 worker가 process 처리를 하지 못했을 때 나타나는 현상입니다!
jobs 채널에 들어갔더라도 process 처리가 시작되지 않았다면 status는 아직 fileuploaded 상태이기 때문에 채널에 중복으로 item이 다시 쌓여요.

중복으로 쌓이게 되면 process가 끝나고 status가 done으로 바뀐 item인데도 다시 processingItem이 실행돼버리는 문제가 있어요.

**Comment by dchecheb** [comment]
jobs 채널 들어간 아이템은 status를 바꿔주는 건 어떨까요?

**Comment by dchecheb** [comment]
이런 식으로요!

```go
// 아이템을 가져와서 버퍼 채널에 채우는 함수
func queueingItem(jobs chan<- Item) {
	for {
		item, err := GetFileUploadedItem()
		if err != nil {
			// 가지고 올 문서가 없다면 10초 기다렸다가 continue
			if err == mongo.ErrNoDocuments {
				time.Sleep(time.Second * 10)
				continue
			}
			// DB에서 아이템을 가지고 오는 과정에서 에러가 발생하면 로그 출력후 10초를 기다리고 다시 진행
			log.Println(err)
			time.Sleep(time.Second * 10)
			continue
		}
		jobs <- item
		// Status 를 작업 대기 중 상태로 변경한다.
		err = SetStatus(client, item, "Queued in Jobs")
		if err != nil {
			return err
		}
		// 10초후 다시 queueing 한다.
		time.Sleep(time.Second * 10)
	}
}
```

**Comment by khw7096** [comment]
일단 채널에 들어갔다면 status 자체를 바꾸어주는 건 좋은것 같아요.
CSI에서도 비슷한 코드가 있는데 살펴봐야겠네요. https://github.com/digital-idea/csi3/blob/9a142a647fc7194ad5a7488f43b050f63be43dbf/process.go#L64

ffmpeg 연산이 10초가 걸리지 않아서 문제가 없었지만.. 혹여 버그가 생길 수 있으니..

**Comment by khw7096** [comment]
저도 해당 이슈로 https://github.com/digital-idea/csi3/issues/1095 이슈를 만들어봤어요.

**Comment by dchecheb** [comment]
그럼 dotori도 `queued` status로 바꿀게요!!
