### ISSUE TITLE
제안: 최초 페이지 New Tags 위에 New Titles 추가하기

### ISSUE THREAD

**Issue by dchecheb** [RD101/dotori#1385]
![Screenshot from 2021-01-26 16-23-28](https://user-images.githubusercontent.com/46209590/105813556-5dc7d100-5ff3-11eb-8879-b3a4615d807d.png)

저희 회사에서 사용해보니까 파일명이 tag로 들어가다보니, tags보다는 Title이 조금 더 유의미한 데이터더라구요! Tags를 Title로 바꾸던가 New Tags 위에 New Title을 추가 하고 싶어요!

**Comment by baesy0** [comment]
저는 New Tags위에 New Titles가 좋은 거 같아요!
그런데 New Items가 아니라 New Titles인 이유는 뭐에요?
Title이 같은 아이템이 많나요?

**Comment by khw7096** [comment]
0001, 230498f 같은건 안들어가는게 좋을듯해요. :-)

**Comment by sar9702** [comment]
저도 New Tags 위에 New Titles가 좋을 거 같아요!

**Comment by dchecheb** [comment]
![image](https://user-images.githubusercontent.com/46209590/105928070-98c81400-6088-11eb-9219-f857331d7ffa.png)
위 사진을 보시면 이해가 가실 것 같아요!
저희가 요즘 기존에 가지고 있던 어셋들을 전부 Dotori에 올리고 있는 작업을 하고 있는데요. 데이터가 워낙 많다보니 지정한 폴더 하위 어셋은 전부 dotori로 올려주는 python 스크립트를 따로 개발해서 이용하고 있어요. 이때 비슷한 이름인 asset들이 정말 많아서, Title은 같게 하고(City, Fireworks ...etc) filename을 tags에 넣어서 이걸 구분해주고 있거든요.

그래서 지금 저희 회사 DOTORI는 같은 title을 가진 asset이 정말 많구요! 이를 구분하기 위해서 tags에 0001, 230498f 이런 태그가 들어가야 하는 상태에요!

**Comment by dchecheb** [comment]
```python
#coding:utf8
# 소스 폴더에서 sequence를 찾아 DOTORI에 Footage로 업로드하는 스크립트

import sys
import os
import glob
import re
import subprocess

def uploadFootage(path):
    '''
    인수로 받아온 path 하위에 있는 모든 시퀀스를 DOTORI에 업로드하는 함수    
    '''
    options = {
                "-title" : "`City`",
                "-author" : "rd101",
                "-itemtype" : "footage",
                "-description" : "",
                "-tag" : "",
                "-premultiply": "",
                "-fps" : "24",
                "-incolorspace" : "",
                "-outcolorspace" : "sRGB",
                "-inputdatapath" : ""
                }
    if not path.endswith("/"):
        path += "/"

    # path 탐색 시작
    cnt = 0
    for folderName in os.listdir(path):
        dirPath = path + folderName
        if os.path.isdir(dirPath):
            cnt += 1
            globStr = dirPath + "/" + folderName + ".*"
            cmd = "dotori -mongodburi mongodb://blar:27017 -add "
            options["-description"] = folderName
            options["-tag"] = folderNameToTags(folderName)

            # 확장자 확인
            if glob.glob(globStr + ".exr"):
                options["-incolorspace"] = "linear"
                options["-inputdatapath"] = "'" + globStr + ".exr'"
            elif glob.glob(globStr + ".dpx"):
                options["-incolorspace"] = "Cineon"
                options["-inputdatapath"] = "'" + globStr + ".dpx'"
            elif glob.glob(globStr + ".jpg"):
                options["-incolorspace"] = "sRGB"
                options["-inputdatapath"] = "'" + globStr[:-1] + "[^t]*.jpg'" 
            else:
                print(folderName + ": None")
                continue

            # cmd 실행
            for opt in options:
                cmd += opt + " " + options[opt] + " "
            print(cmd)
            subprocess.call(cmd, shell=True)

            # 썸네일 확인
            movFiles = glob.glob(globStr + ".mov")
            if movFiles:
                for movFile in movFiles:
                    if "thumb" in movFile or "thum" in movFile:
                        pass
                    else:
                        print(folderName + ": source mov")
            nkFiles = glob.glob(globStr + ".nk")
            if nkFiles:
                for nkFile in nkFiles:
                    if "thumb" in nkFile or "thum" in nkFile:
                        pass
                    else:
                        print(folderName + ": source nk")


def folderNameToTags(folderName):
    '''
    folder 이름을 tag string으로 변환해주는 함수
    '''
    # tagList = re.split(" |,|_|-", folderName)
    tagList = re.split("[_ ',-.]", folderName)
    for tag in tagList:
        if len(tag) == 1:
            tagList.remove(tag)
    return "'" + " ".join(tagList) + "'"


if __name__ == "__main__":
    print("Enter a upload path >")
    path = sys.stdin.readline().rstrip()
    uploadFootage(path)
```
이건 저희가 지금 업로드에 사용하고 있는 python 스크립트에요.

**Comment by dchecheb** [comment]
```python
#coding:utf8
# 소스 폴더에서 sequence를 찾아 DOTORI에 Footage로 업로드하는 스크립트

import sys
import os
import glob
import re
import subprocess

def uploadFootage(path):
    '''
    인수로 받아온 path 하위에 있는 모든 시퀀스를 DOTORI에 업로드하는 함수    
    '''
    options = {
                "-title" : "City",
                "-author" : "rd101",
                "-itemtype" : "footage",
                "-description" : "",
                "-tag" : "",
                "-premultiply": "",
                "-fps" : "24",
                "-incolorspace" : "",
                "-outcolorspace" : "sRGB",
                "-inputdatapath" : ""
                }
    if not path.endswith("/"):
        path += "/"

    # path 탐색 시작
    cnt = 0
    for folderName in os.listdir(path):
        dirPath = path + folderName
        if os.path.isdir(dirPath):
            cnt += 1
            globStr = dirPath + "/" + folderName + ".*"
            cmd = "dotori -mongodburi mongodb://blahblah:27017 -add "
            options["-description"] = folderName
            options["-tag"] = folderNameToTags(folderName)

            # 확장자 확인
            if glob.glob(globStr + ".exr"):
                options["-incolorspace"] = "linear"
                options["-inputdatapath"] = "'" + globStr + ".exr'"
            elif glob.glob(globStr + ".dpx"):
                options["-incolorspace"] = "Cineon"
                options["-inputdatapath"] = "'" + globStr + ".dpx'"
            elif glob.glob(globStr + ".jpg"):
                options["-incolorspace"] = "sRGB"
                options["-inputdatapath"] = "'" + globStr[:-1] + "[^t]*.jpg'" 
            else:
                print(folderName + ": None")
                continue

            # cmd 실행
            for opt in options:
                cmd += opt + " " + options[opt] + " "
            print(cmd)
            subprocess.call(cmd, shell=True)

            # 썸네일 확인
            movFiles = glob.glob(globStr + ".mov")
            if movFiles:
                for movFile in movFiles:
                    if "thumb" in movFile or "thum" in movFile:
                        pass
                    else:
                        print(folderName + ": source mov")
            nkFiles = glob.glob(globStr + ".nk")
            if nkFiles:
                for nkFile in nkFiles:
                    if "thumb" in nkFile or "thum" in nkFile:
                        pass
                    else:
                        print(folderName + ": source nk")


def folderNameToTags(folderName):
    '''
    folder 이름을 tag string으로 변환해주는 함수
    '''
    # tagList = re.split(" |,|_|-", folderName)
    tagList = re.split("[_ ',-.]", folderName)
    for tag in tagList:
        if len(tag) == 1:
            tagList.remove(tag)
    return "'" + " ".join(tagList) + "'"


if __name__ == "__main__":
    print("Enter a upload path >")
    path = sys.stdin.readline().rstrip()
    uploadFootage(path)
```
이건 footage 한 번에 업로드하는 데 사용 중인 python 스크립트에요.

**Comment by dchecheb** [comment]
> 저는 New Tags위에 New Titles가 좋은 거 같아요!
> 그런데 New Items가 아니라 New Titles인 이유는 뭐에요?
> Title이 같은 아이템이 많나요?

**Comment by khw7096** [comment]
타이틀이 같은게 굉장히 아쉽네요.

City0001, City0002 로만 가도 좋을텐데..

**Comment by khw7096** [comment]
이런 상황에서 왜 New Titlte 에대 추가를 원하는지 이해가 갔어요.

**Comment by baesy0** [comment]
> 이런 상황에서 왜 New Titlte 에대 추가를 원하는지 이해가 갔어요.

ㅇㅇ저두요
저장해둔 에셋을 검색할 때, 어떤 방식이 효과적일지에 대한 고민이 필요할 거 같아요.
현재 태그는 나중에 검색할 때 큰 효용이 있을 거 같지는 않아요.
실제로 사용할 때는 어때요?

**Comment by khw7096** [comment]
저 역시.. "신경쓴 태그명과 제목은 먼 미래에 여러분을 힘들게 하지 않을 것 입니다."

**Comment by baesy0** [comment]
근데 한 편으로는 사용자가 어떤 식으로 사용하든 편한 툴이긴 했으면 좋겠어요.
'사용자가 이런 식으로 사용했으면 좋겠다'는 마음이 있다면 툴에서 먼저 가이드를 제시해주는게 좋을 것 같아요.
- '좋은 사용을 위해서는 태그를 체계적으로 사용해야 한다'고 적어둔다.
- 좋은 사용 예시를 보여준다.

위와 같은 방법도 일종의 간접적인 가이드가 되어줄 것 같아요.
사용자에게 아예 자유를 줄거라면 툴에서 어느 정도는 편리한 사용을 도와줘야하지 않을까 싶기도 해요.

**Comment by dchecheb** [comment]
> 근데 한 편으로는 사용자가 어떤 식으로 사용하든 편한 툴이긴 했으면 좋겠어요.
> '사용자가 이런 식으로 사용했으면 좋겠다'는 마음이 있다면 툴에서 먼저 가이드를 제시해주는게 좋을 것 같아요.
> 
> * '좋은 사용을 위해서는 태그를 체계적으로 사용해야 한다'고 적어둔다.
> * 좋은 사용 예시를 보여준다.
> 
> 위와 같은 방법도 일종의 간접적인 가이드가 되어줄 것 같아요.
> 사용자에게 아예 자유를 줄거라면 툴에서 어느 정도는 편리한 사용을 도와줘야하지 않을까 싶기도 해요.

정말 좋은 의견인 것 같아요. 전적으로 동의해요!

DOTORI의 장점인 자율성은 유지하되 이용을 저희가 원하는 방향으로 유도할 수 있는 방법을 생각해보면 좋을 것 같아요. 사용자 이용 패턴(검색 방식, 업로드 시 title, tags 형식 등)이 개발하면서 예상했던 패턴에서 심각하게 벗어난다면 분명 비효율이 발생할테니까요.

**Comment by dchecheb** [comment]
다만 제가 진행 중인 footage 대량 업로드 건(약 10000~15000개)은 상황이 조금 달라요.
이번 어셋 업로드 건에서 가장 중요한 점 2가지는 다음과 같아요.
- 검색 시, 비슷한 모양의 어셋이 뭉쳐서 나오도록 한다.
- 최대한 빨리 업로드한다.

비슷한 파일 이름의 어셋들은 대부분 비슷한 모양을 가지고 있기 때문에 filename이 태그로 들어가요. 
아래 이미지처럼 cloud 소스를 찾고자 했을 때 cloud라고 검색을 한 후, vfxcentral이나 storm 태그를 클릭하면 비슷한 모양의 어셋을 뭉쳐서 볼 수 있어요! 저도 vfxcentral 같은 애들이 tag로 들어가는 건 좋지 않다고 보지만(따흙흙..ㅠ) 현재 저희 기존 어셋들 상태에서 비슷한 모양의 어셋을 뭉쳐서 볼 수 있게 하기 위해서는 이게 가장 좋은 방법이라 생각했어요.

또한, python으로 자동 업로드를 하다보니 filename 외의 태그는 달지 못하고 있는 상태에요.
뭔가 더 좋은 방법은 확실히 있을 것 같은데... 아직은 생각이 잘 안나네요.
![Screenshot from 2021-01-29 12-21-42](https://user-images.githubusercontent.com/46209590/106228184-327cf600-622e-11eb-936b-956f79964189.png)

**Comment by dchecheb** [comment]
지금 위 이미지를  다시 보니 태그들 중 cloud, Cloud처럼 같은 이름이지만 대소문자만 다른 태그는 중복이라 보고 제외해야겠네요. 
저희 검색은 대소문자를 구분하지 않으니까요!

**Comment by dchecheb** [comment]
일단 결론적으로 같은 title이 많은 것은 사실 지양해야할 방식이니 New Tags를 New Titles로 굳이 바꿀 필요는 없을 것 같네요!

**Comment by baesy0** [comment]
그러면 일단
- 태그의 대소문자를 구분하지 않도록 하기.
- 좋은 사용 예시를 추가하기

를 따로 이슈로 빼면 될 거 같아요

**Comment by baesy0** [comment]
> 다만 제가 진행 중인 footage 대량 업로드 건(약 10000~15000개)은 상황이 조금 달라요.
> 이번 어셋 업로드 건에서 가장 중요한 점 2가지는 다음과 같아요.
> 
> * 검색 시, 비슷한 모양의 어셋이 뭉쳐서 나오도록 한다.
> * 최대한 빨리 업로드한다.
> 
> 비슷한 파일 이름의 어셋들은 대부분 비슷한 모양을 가지고 있기 때문에 filename이 태그로 들어가요.
> 아래 이미지처럼 cloud 소스를 찾고자 했을 때 cloud라고 검색을 한 후, vfxcentral이나 storm 태그를 클릭하면 비슷한 모양의 어셋을 뭉쳐서 볼 수 있어요! 저도 vfxcentral나 0001 같은 애들이 tag로 들어가는 건 좋지 않다고 보지만(따흙흙..ㅠ) 현재 저희 기존 어셋들 상태에서 비슷한 모양의 어셋을 뭉쳐서 볼 수 있게 하기 위해서는 이게 가장 좋은 방법이라 생각했어요.
> 
> 또한, python으로 자동 업로드를 하다보니 filename 외의 태그는 달지 못하고 있는 상태에요.
> 뭔가 더 좋은 방법은 확실히 있을 것 같은데... 아직은 생각이 잘 안나네요.
> ![Screenshot from 2021-01-29 12-21-42](https://user-images.githubusercontent.com/46209590/106228184-327cf600-622e-11eb-936b-956f79964189.png)

“대량의 에셋을 코드로 자동 업로드할 때, 어떻게 좋은 태그를 설정할 것인가.”
같은 문제로 이해했는데 맞나요?

**Comment by dchecheb** [comment]
> “대량의 에셋을 코드로 자동 업로드할 때, 어떻게 좋은 태그를 설정할 것인가.”
> 같은 문제로 이해했는데 맞나요?

넵 근데 이건 사실 대량의 어셋을 자동으로 업로드해야하는 이슈가 있는 회사에서 고민해야 할 문제 같아요!

**Comment by baesy0** [comment]
그러면 이 부분은 회사 내부적으로 해결되지 않고 툴에 추가해야 할 것이 생겼을 때, 토론해보면 좋을 거 같아요!
그 때가 되면 구체적인 주제의 이슈를 열어서 이야기해보아요:)

어느 정도 결론이 정리된 것 같으니 이 이슈는 닫을게요!
