### ISSUE TITLE
R3D 파일은 아이템 타입을 추가할까요? 아니면 footage로 넣는 게 좋을까요?

### ISSUE THREAD

**Issue by dchecheb** [RD101/dotori#1386]
.R3D는 촬영 원본 파일이라고 들었습니다!

**Comment by dchecheb** [comment]
footage에서 .R3D 파일이면 썸네일 다른 방식으로 뽑는 게 가장 깔끔할 것 같긴 해요

**Comment by khw7096** [comment]
R3D 파일을 바로 저장하는 이유는 모예요? 보통 백업할 때 추후 아티스트, 렌더아티스트등 즉각적인 재활용성을 위해서 EXR로 컨버팅하는걸 추천해요.
- R3D 데이터의 경우 최신파일은 항상 레드사의 컨버팅툴을 사용해서 컨버팅해야하는 상황이 발생하기도 하구요~
- 두번째는 회사 스토리지가 남아나지 않을것 같아서... :-)

**Comment by dchecheb** [comment]
아하 감사해요 지금 안그래도 ffmpeg로 .r3d 파일 컨버팅하는 것도  버전문제로 계속 실패하고 있었어요. 용량도 굉장히 크더라구요. R3D는 exr로 컨버팅한 후에 올리는 것으로 할게요!
