### ISSUE TITLE
Process: 프로세스 페이지에 아이템 타이틀 추가하기

### ISSUE THREAD

**Issue by sar9702** [RD101/dotori#1396]
프로세스 페이지에서도 Clean up 페이지와 비슷하게 아이템의 타이틀을 확인할 수 있도록 하는 건 어떨까요?
item type, author, id, status만 있다보니깐 이 페이지에서만 보면 어떤 아이템이 진행중인지 확인이 힘든 거 같아서요..

**Comment by khw7096** [comment]
찬성해요~ :-)
