### ISSUE TITLE
에셋이 많아졌을 때 페이지 번호가 넘치는 문제 해결하기

### ISSUE THREAD

**Issue by sar9702** [RD101/dotori#1398]
![dotori](https://user-images.githubusercontent.com/14924389/111095851-a9bddd80-8581-11eb-84d3-91db276766ec.png)

**Comment by khw7096** [comment]
![](https://blog.codinghorror.com/content/images/uploads/2012/03/6a0120a85dcdae970b0167644e1bbe970b-800wi.png)

이러한 방식을 고민할 때가 왔군요~!

**Comment by khw7096** [comment]
- 첫페이지 표기
- 끝페이지 표기
- 현재 기준 몇개를 보여줄 지 offset 설정

**Comment by sar9702** [comment]
네네 저도 떠오르는게 있으면 적어볼게요!!

**Comment by sar9702** [comment]
우선 이런식으로 첫페이지, 끝페이지, 1개씩 이동하는 버튼만 추가해보려고 하는데 어떠신가요?

![paging1](https://user-images.githubusercontent.com/14924389/116845480-ec667280-ac20-11eb-9d4a-7b238cc11113.png)

![dotori_paging2](https://user-images.githubusercontent.com/14924389/116845438-d48eee80-ac20-11eb-9b4a-55b85e548a4d.png)

10페이지씩 이동하는건 내부에서 얘기해봤는데 에셋을 찾을 때 10 페이지씩 이동하면서 찾는 경우는 없을 거 같다는 얘기가 나와서 우선은 필요한 기능 먼저 추가해보려구요!

**Comment by khw7096** [comment]
좋아요. 크게 고치는 것 보다, 작게작게 고치는것 좋다고 생각합니다.
