### ISSUE TITLE
Copy Path 버튼을 클릭했을 때 경로가 복사되었다는 메시지가 떴으면 좋겠다.

### ISSUE THREAD

**Issue by sar9702** [RD101/dotori#1400]

**Comment by khw7096** [comment]
최근에 CSI에도 이 기능이 들어갔어요. :-)

**Comment by sar9702** [comment]
오와 구경가야겠네요!!ㅋㅋㅋ

**Comment by khw7096** [comment]
구경와요. https://github.com/digital-idea/csi3/blob/416db1553786a2ec8a6c1e6ddf545ccec53b1386/assets/js/input.js#L5517
