### ISSUE TITLE
유저 비밀번호 초기화하는 기능

### ISSUE THREAD

**Issue by sar9702** [RD101/dotori#1401]
저희 사용자가 비밀번호를 잃어버렸을 때 초기화해주는 기능을 추가했었나요...?

**Comment by khw7096** [comment]
아니요. 도토리에는 추가한적이 없어요.

**Comment by sar9702** [comment]
흠 도토리에서도 admin 권한을 가진 사람이 유저들의 액세스레벨과 비밀번호를 초기화할 수 있는 페이지가 있으면 좋을 거 같은데 어떠신가요??

**Comment by khw7096** [comment]
전 찬성이예요. :-)

**Comment by 78963l** [comment]
+2

**Comment by sar9702** [comment]
넵 그럼 위의 기능들을 할 수 있는 페이지 추가해볼게요!!ㅎㅎ

**Comment by sar9702** [comment]
> 아니요. 도토리에는 UX 적으로 추가한적이 없어요.
> CSI에서 이 기능은 지난주 좀더 편리하게 유저를 선택하고, 패스워드를 초기화 하는 기능을 만들었어요.
> 혹시나 기능개선에 도움이 될까해서 PR 링크를 보내요. 이 기능에 대해 다음주 화요일에 동영상을 만들어요. 관심이 있다면 보내줄께요. 코드를 이해할 때 더 도움이 될 수 있을 것 같아요.
> 
> https://github.com/digital-idea/csi3/pull/1219/files

참고하면 좋을 거 같아요!!

**Comment by khw7096** [comment]
그럼 다움주 기업에 발송을 위한 동영상과 설명을 카카오톡으로 발송할때 같이 보내드릴께요.

**Comment by sar9702** [comment]
> 그럼 다움주 기업에 발송을 위한 동영상과 설명을 카카오톡으로 발송할때 같이 보내드릴께요.

감사합니다!!ㅎㅎ

**Comment by dchecheb** [comment]
#1334 
이슈만 열려있어요!

**Comment by khw7096** [comment]
위 이슈는 사용자가 자신의 패스워드를 바꾸는 기능이고(#1334),
초기화 기능은 패스워드를 까먹어서 관리자가 초기화 해줘야하는 상황 같아요.

**Comment by sar9702** [comment]
> 위 이슈는 사용자가 자신의 패스워드를 바꾸는 기능이고(#1334),
> 초기화 기능은 패스워드를 까먹어서 관리자가 초기화 해줘야하는 상황 같아요.

네네 맞아요! 사용자가 비밀벚호를 까먹어서 다시 회원가입을 하고 있는 상황이 발생해서...ㅋㅋㅋ
