### ISSUE TITLE
요청 : 아이템 타입을 정리 하였으면 좋겠다

### ISSUE THREAD

**Issue by 78963l** [RD101/dotori#1408]
소프트웨어랑 sound, footage 등.. 혼재되어 있고,
타입을 나누지 않고 업로드 하였으면 좋겠다는 의견. (타입별로 코드가 상이해서 하나로 만들기는 시간이 오래걸린다는 답변을 함)

**Comment by khw7096** [comment]
저도 타입별로 처리해야하는 프로세스가 달라지기 때문에 힘들것 같아요.

**Comment by khw7096** [comment]
이 이슈는 닫습니다.
