### ISSUE TITLE
포맷: Matte팀이 사용하는 소스를 올릴 수 있는 포맷이 필요하다.

### ISSUE THREAD

**Issue by sar9702** [RD101/dotori#1432]
Matte팀에서 사용하는 소스들을 올릴 수 있는 포맷이 필요하다고 하는데,
주로 jpg인 경우가 많고, hdri 확장자 파일일 수도 있다고 해요.

소스들은 예를 들면 고속 도로 사진, 멍 사진 이런 1 ~ 2장 정도의 소스들인데, 이런 소스에 맞는 포맷이 없어서 추가하려고 하는데...

지금 hdri 포맷은 따로 있어서 Matte팀에서는 하나의 포맷으로 묶어져 있으면 편할 거 같다고 해서
Matte 포맷을 추가하고, 거기에는 jpg, png, hdri 등의 확장자를 수용할 수 있도록 하려고 하는데 어떻게 생각하시나요??

**Comment by khw7096** [comment]
개인적으로 Matte 단어는 업무의 Task라서 포멧에 추가되면 툴의 정체성이 모호해질 것 같아요. 하지만 왜 그러한 니즈가 생겼는지 알것 같아요. 고민해봐요.

**Comment by khw7096** [comment]
url 별로 사실 툴을 별도로 짜고 있어서.. 개인적으로는 커스텀 페이지로 만들어도 툴에 아무 문제가 없다고 생각해요. :-) 구조는 이상하지만 matte로 만드는게 왠지 더 시장에 잘 먹힐지도!!!!!!!!
