### ISSUE TITLE
sound: mp3 파일 허용하게 하기

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#1464]
- 기본 철학. 모든 파일의 제약이 없어야 한다.

**Comment by khw7096** [comment]
잘 되었나요? 최근에 음원을 사서 업로드 하는데 에러가 떠서요.

<img width="624" alt="image" src="https://user-images.githubusercontent.com/1149996/155041526-69d72c6c-f3b3-42b2-8709-e422cdea8dec.png">

**Comment by sar9702** [comment]
아하 샘플 mp3 파일로 해보니깐 잘 되길래 이게 아닌가? 했어요ㅋㅋㅋ
그럼 저도 다른 이슈 먼저 처리해보겠습니다!

**Comment by khw7096** [comment]
회사에서 구매한 음원을 잘 보관하기 위해서 기능 확장하기.

**Comment by khw7096** [comment]
지원 완료.
