### ISSUE TITLE
질문있습니다! 파일을 추가하는 페이지 함수에 관한 것입니다.

### ISSUE THREAD

**Issue by 78963l** [RD101/dotori#163]
http_add.go 파일에서 handleAddMaya함수, handleAddHoudini함수, handleAddBlender함수, handleAddABC함수, handleAddUSD함수 전부 같은 기능을 하는 함수인데 나누는 이유가 궁금합니다. 나중에 각자 다른 코드가 들어 갈 수도 있어서 분리하는 것인가요??

**Comment by khw7096** [comment]
네 맞아요~!

**Comment by 78963l** [comment]
> 네 맞아요~!

아하! 감사합니다.

**Comment by khw7096** [comment]
장단점이 있는데..

장점: 추후 버그발생시 해당 파일 부분만 에러가 날것이다. 마야 업로드부분이 문제가 생겼을 때 뉴크 라이브러리는 에러가 나지 않겠죠.
단점: 중복코드가 꽤 있다.

**Comment by 78963l** [comment]
> 장단점이 있는데..
> 
> 장점: 추후 버그발생시 해당 파일 부분만 에러가 날것이다. 마야 업로드부분이 문제가 생겼을 때 뉴크 라이브러리는 에러가 나지 않겠죠.
> 단점: 중복코드가 꽤 있다.

아하 그런장점도 있군요.

**Comment by 78963l** [comment]
> 장단점이 있는데..
> 
> 장점: 추후 버그발생시 해당 파일 부분만 에러가 날것이다. 마야 업로드부분이 문제가 생겼을 때 뉴크 라이브러리는 에러가 나지 않겠죠.
> 단점: 중복코드가 꽤 있다.

그럼 추후에 중복코드는 묶는것도 괜찮지않을까요?

**Comment by 78963l** [comment]
> 장단점이 있는데..
> 
> 장점: 추후 버그발생시 해당 파일 부분만 에러가 날것이다. 마야 업로드부분이 문제가 생겼을 때 뉴크 라이브러리는 에러가 나지 않겠죠.
> 단점: 중복코드가 꽤 있다.

중복코드가 좋지 않다고만 알고 있어서,, 중복코드였다면 장점에서 마야업로드 부분이 문제생겼을때 다른업로드 부분에서도 같은 에러가 나지않을까요..?

**Comment by khw7096** [comment]
모여서 같이 이야기해봐용~!! 중복코드를 없애기 가장 좋은 방법은 그 부분을 한사람이 작성하는 거예요~ :-)

**Comment by 78963l** [comment]
> 모여서 같이 이야기해봐용~!! 중복코드를 없애기 가장 좋은 방법은 그 부분을 한사람이 작성하는 거예요~ :-)

알겠습니다~

**Comment by khw7096** [comment]
분리로 갑니다.
모든 코드가 잘 돌아가고 안정적으로 서비스가 돌아갈 때 코드 리펙토링을 진행합니다.
