### ISSUE TITLE
프로세스 페이지에서 아이템 삭제 후 모달창이 닫히면 좋을 것 같다.

### ISSUE THREAD

**Issue by sar9702** [RD101/dotori#1680]
프로세스 페이지에서 아이템 삭제하면 모달창은 그대로 남아 있던데 혹시 그렇게 한 이유가 있는 걸까요???

![dotori_bug](https://user-images.githubusercontent.com/14924389/206335142-1c78df6a-1170-4885-9996-af348237aae5.png)

**Comment by khw7096** [comment]
아니요. 버그예요. :-)
