### ISSUE TITLE
Maya example 파일로 upload-maya 함수 테스트 하기

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#176]

**Comment by baesy0** [comment]
## mime type 체크
- .ma: application/octet-stream
- .mb: application/octet-stream
- .jpg: image/jpeg
- .mov: video/quicktime

**Comment by baesy0** [comment]
## 권한 체크
- 766을 줘도 744로 생성됨.
```go
err = os.MkdirAll(path, 0766)
```
<img width="703" alt="image" src="https://user-images.githubusercontent.com/40417084/73707641-864e1f80-473f-11ea-8b12-5c31f11a49db.png">

- write 권한이 부여되지 않음.

설정한 권한|실제 생성된 권한
:-----:|:-----:
766|744
777|755
744|744
711|711
722|700

**Comment by baesy0** [comment]
- 권한 문제를 제외하면 나머지는 잘 실행됩니다.
<img width="644" alt="image" src="https://user-images.githubusercontent.com/40417084/73708499-e47c0200-4741-11ea-8f7e-8d8b668bbe73.png">

**Comment by khw7096** [comment]
umask 값을 체크해 보아요.

**Comment by baesy0** [comment]
오 그런게 있군! 넹넹

**Comment by baesy0** [comment]
umask때문인거 같긴한데
그냥 umask는 변경이 되는데 sudo umask를 했을 땐 변경이 안되서 테스트를 못해보고 있어요
<img width="570" alt="image" src="https://user-images.githubusercontent.com/40417084/73722976-308f6c80-476b-11ea-93bf-a62cd3acf6a7.png">

**Comment by baesy0** [comment]
그런데 찾아봤을 때 umask는 보안때문에 생긴거라는데, 이걸 수정하면서까지 766, 666권한을 줘야 하나요?
이 단계에서 write권한이 필요한 이유가 있나요?

**Comment by khw7096** [comment]
아직은 변경까지 하면서 할 필요는 없을 것 같아요.
