### ISSUE TITLE
썸네일 디자인 아이디어

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#179]
- 아이템 수정버튼, 겸 디테일 페이지
- 마우스를 올리면 동영상이 플레이된다.
- 다운로드 버튼
- 사용빈도수 숫자는 출력되도록 하기
- 태그 출력
- 제작자
- 폴더 바로 열기
- 플레이어로 바로 재생
- 임폴트 마야 되도록 하기.
    - 마야 help 프로토콜 체크하기.
    - RestAPI 이용방법
    - 마야 내부 브라우저에서 도토리 실행하는 방법
    - dilink처럼 클릭하면 툴이 뜨도록 하는 방법

**Comment by baesy0** [comment]
- AR 아이콘

**Comment by ChaeyunBae** [comment]
### 검색 페이지
<img width="1251" alt="스크린샷 2020-05-31 오후 6 30 48" src="https://user-images.githubusercontent.com/46209590/83349113-368a0880-a36d-11ea-95e4-0876f4a13425.png">

**Comment by ChaeyunBae** [comment]
<img width="1250" alt="스크린샷 2020-05-31 오후 6 30 55" src="https://user-images.githubusercontent.com/46209590/83349122-4efa2300-a36d-11ea-9c96-3ef00afbd25f.png">

**Comment by ChaeyunBae** [comment]
<img width="1253" alt="스크린샷 2020-05-31 오후 6 31 01" src="https://user-images.githubusercontent.com/46209590/83349128-5d483f00-a36d-11ea-8c77-953f89239ec6.png">

**Comment by ChaeyunBae** [comment]
이런 재질 어떠시유

**Comment by baesy0** [comment]
재질ㅋㅋㅋ
- usingrate이 보이면 좋겠어요! 좋은 에셋인지 판단의 기준이 될 거 같아서요.
- 자주 쓰는 건 보자마자 다운로드할 수 있게 다운로드 버튼을 밖으로 빼면 좋을 거 같아요

**Comment by baesy0** [comment]
모달 페이지는 기기에 따라 다르게 보일 것 같다
