### ISSUE TITLE
item 수정할 때 쓸  REST API 만들기

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#187]
수정할 때 쓸 rest api가 필요할 거 같아요.
기존의 handleAPIItem에 PATCH 메소드를 추가하는 거 어때요?

**Comment by baesy0** [comment]
그러면 dbapi.go에 updateItem함수가 필요할 거 같아요

**Comment by khw7096** [comment]
patch 메소드 추가하는것 좋아요.

**Comment by khw7096** [comment]
submit 방식으로 진행하기 때문에 필요없을 것 같아요. 닫습니다.
