### ISSUE TITLE
메타데이터에 있는 정보중, 핵심적인 정보는 자동으로 태깅되도록 하기

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#19]

**Comment by khw7096** [comment]
#### 핵심적인 정보를 얻는 명령어
- exr: exrheader
- usd: sdfdump

**Comment by khw7096** [comment]
해당 정보를 실제로 만나면 그때 이슈를 다시 오픈한다. 이 이슈는 현재 추상적이다.
