### ISSUE TITLE
admin 셋팅추가: 폴더를 만들 때 권한에 필요한 변수 추가.

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#217]

**Comment by baesy0** [comment]
- UID
- GID
- permission
- umask

**Comment by khw7096** [comment]
dotori.setting.admin 에 저장한다.

**Comment by khw7096** [comment]
- umask값이 등록되면 앞으로 도토리의 빌드는 리눅스, 맥만 진행한다.
- 윈도우즈는 umask 값을 사용할 수 없다.
- 어짜피 윈도우즈10은 20명까지만 동시접속자를 허용하지 않기 때문에 서버로서 의미가 없다.

**Comment by khw7096** [comment]
CSI를 제작할 때 작성된 코드를 참조할 것.

**Comment by khw7096** [comment]
저장될 스토리지의 위치

**Comment by khw7096** [comment]
한 페이지당 출력될 아이템수가 설정이 있으면 서비스를 재시작하지 않고 처리할 수 있다.
