### ISSUE TITLE
동시에 여러 사람이 에셋을 등록할 때 고려해야할 사항.

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#240]
동시에 에셋을 업로드 한다면 업로드 폴더가 한곳에 집중되어 있으면 안된다.
- 접속한 사용자의 IP를 이용하는 방법 - 1차구현
- 접속한 사용자의 id를 이용하는 방법 - 로그인이 필요하다. - 2차구현

**Comment by baesy0** [comment]
1차를 IP로 한다.

**Comment by baesy0** [comment]
#275 에서 다시 논의
