### ISSUE TITLE
어떤 status를 만들지 회의

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#253]
- 복사전:  Ready
- 복사중: Copying
- 복사 완료: Copied
- 등록 완료: Done
- 썸네일 생성중: CreatingThumbnail
- 썸네일 생성완료: CreatedThumbnail
- 썸네일 동영상 생성중: CreatingContainer
- 썸네일 동영상 생성완료: CreatedContainer

**Comment by khw7096** [comment]
참고: https://github.com/digital-idea/csi3/blob/master/project.go#L10
