### ISSUE TITLE
GetReadyItem으로 아이템을 받아옴과 동시에 아이템의 상태가 변경되어야 함

### ISSUE THREAD

**Issue by kybin** [RD101/dotori#291]
현재 processItem은 GetReadyItem으로 ready 상태인 아이템을 하나 가져온 후 다른 함수에서 이 항목의 상태를 변경하려는 것처럼 보입니다. 이럴 경우 동시에 processItem이 N번 호출될 경우 같은 항목을 N번 복사하게 될 수 있습니다. 

그래서 제 생각에 GetReadyItem은 ready 상태인 아이템을 가져오는 동시에 이 아이템의 상태를 다음 상태로 변경해야 합니다. 이는 함수 수준이 아니라 정말로 동시에 이루어져야 하고, 이를 위해 mongodb의 transaction 기능을 사용하던지, mutex.Lock을 사용할 수 있습니다. 더 나은 솔루션은 transaction 인것으로 보이지만 혹시 몰라 mutex도 남겨놓습니다.

**Comment by khw7096** [comment]
https://stackoverflow.com/questions/54398579/example-for-transactions-in-mongodb-with-golang

**Comment by khw7096** [comment]
- mgo 방식
- mongo driver 방식

**Comment by baesy0** [comment]
20일만에 돌아왔다!! 시작해봅니다.. 후후..

**Comment by baesy0** [comment]
5일 전에 왔던 각설이 죽지않고 또 돌아옴..
mongo driver 방식으로 다시 해봅니다

**Comment by baesy0** [comment]
issue #386

**Comment by baesy0** [comment]
이슈 공유 완료. Transaction 진행 중. 이슈 닫을게요:)
