### ISSUE TITLE
status 추가

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#292]
상태와 상태 사이를 나타낼 status 필요
- occupied

**Comment by baesy0** [comment]
흠 몇 번째로 추가하는게 좋을까요

**Comment by khw7096** [comment]
상태는 많아져도 상관없을 듯해요. 명확하게 Status와 Status 사이를 명시하면좋을 것 같아요.
지금 결정하지 않고, 실제로 파일 업로드하고 버그 고치면서 실제로 필요한 상태를 추가하는 것도 방법일듯해요.

**Comment by baesy0** [comment]
네 저도 동의해요. 그리고 트렌젝션 기능을 추가한 후에 정말 status사이에 애매한 기간이 있는지 보고 진행하는 것도 좋을 거 같아요.
