### ISSUE TITLE
참고자료: Go file upload

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#308]
https://tutorialedge.net/golang/go-file-upload-tutorial/

**Comment by khw7096** [comment]
dropzone의 경우 제한되는 것들..

dropzone.js 파일에 선언되어있는 값.

```javascript
chunkSize: 2000000,
maxFilesize: 256,
filesizeBase: 1000,
```

**Comment by khw7096** [comment]
- 우리가 앞으로 다루게 될 데이터는 동시 업로드가 10000개가 넘는 파일일 수 있다.
- 파일의 사이즈가 굉장히 클 수 있다.

**Comment by khw7096** [comment]
무거운 파일을 업로드 할 수 있는 상황에서는 dropzone 말고 직접 구현하는 것에 대해 토론하기.

**Comment by baesy0** [comment]
```
/**
         * Whether to send multiple files in one request. If
         * this it set to true, then the fallback file input element will
         * have the `multiple` attribute as well. This option will
         * also trigger additional events (like `processingmultiple`). See the events
         * documentation section for more information.
         */
        uploadMultiple: false,
```
이런 옵션이 있어요

**Comment by baesy0** [comment]
go를 이용한 multiple file upload example
https://socketloop.com/tutorials/upload-multiple-files-golang

**Comment by baesy0** [comment]
dropzone의 옵션 중
```
parallelUploads: 2,
uploadMultiple: false,
```
이 두 값이 핸들러 함수의 실행횟수에 영향을 미치고 있어요.

1. uploadMultiple이 false인 경우
    - parallelUploads의 값과 상관없이 업로드한 파일의 개수만큼 함수를 실행

1. uploadMultiple이 true인 경우
    - 업로드한 파일의 개수 / parallelUploads (나누어 떨어지지 않는 경우 +1) 만큼 함수를 실행


uploadMultiple|parallelUploads|업로드한 파일 개수|함수 실행 횟수
:---:|:---:|:---:|:---:
false|2|4|4
false|4|8|8
false|3|8|8
true|2|4|2
true|4|4|1
true|4|7|2
true|4|8|2
true|4|9|3
true|8|7|1
true|8|8|1
true|8|9|2

**Comment by khw7096** [comment]
Preps to you~

**Comment by baesy0** [comment]
hihi Thx;)

**Comment by baesy0** [comment]
업로드 가능한 파일 개수 옵션
```
maxFiles: null,
```

**Comment by baesy0** [comment]
```
parallelUploads: 2,
uploadMultiple: false,
maxFiles: null,
```
위 세 옵션을 조합하면 될 거 같아요.

**Comment by baesy0** [comment]
- thumbnail
- preview
- Maya file
넉넉하게 5개로 하기로
```
parallelUploads: 5,
uploadMultiple: true,
maxFiles: 5,
```

**Comment by baesy0** [comment]
함수 실행 한 번만 되는 거 done!

**Comment by baesy0** [comment]
objectID 경로도 done!
