### ISSUE TITLE
서버용량체크meta:서버에 용량이 없다면 업로드 되면 안된다.

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#310]

**Comment by khw7096** [comment]
https://gist.github.com/lunny/9828326

**Comment by 78963l** [comment]
https://ispycode.com/GO/System-Calls/Disk-Usage

**Comment by 78963l** [comment]
syscall이 없어 syscall "golang.org/x/sys/unix"으로 import 후에 생기는 오류
![werewrwewewer](https://user-images.githubusercontent.com/46780796/76698820-96680000-66ea-11ea-9027-6dd59fd7b8aa.PNG)

**Comment by 78963l** [comment]
go 문서에는 함수가 있음.
![werwreewrwe](https://user-images.githubusercontent.com/46780796/76699142-ae8d4e80-66ed-11ea-9701-d3115f0a5d58.PNG)

**Comment by khw7096** [comment]
오오~

**Comment by 78963l** [comment]
https://docs.mongodb.com/manual/reference/command/dbStats/

**Comment by baesy0** [comment]
오오오

**Comment by khw7096** [comment]
저는 Go 방식을 쓰는게 더 좋을듯해요. DB는 나중에 용도에 따라 바뀔 수도 있으니..

**Comment by 78963l** [comment]
![image](https://user-images.githubusercontent.com/46780796/76920564-1f5f8100-690f-11ea-9c47-d40da3e09d05.png)
Unix 계열에선 사용가능

**Comment by khw7096** [comment]
windows10으로는 컴파일하지 않을 예정이예요. 해당 코드를 사용해도 좋아요.

**Comment by khw7096** [comment]
해당 usb 또는 마운트 포인트도 테스트 되는지 확인해보세요. 아마우리가 도토리를 쓰게될 때는 스토리지가 마운트 될 확률이 높으니까요.

**Comment by 78963l** [comment]
넵 알겠습니당!

**Comment by khw7096** [comment]
이 이슈로 필요한 함수가 만들어짐. 이 이슈를 닫습니다.
