### ISSUE TITLE
uploadMayaOnDB함수에서 inputpath, outputpath 부분 리팩토링

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#317]
dotori폴더에 하위폴더가 생겼기 때문에 리팩토링이 필요하다.
outputpath도 아이템의 objectID를 이용한 경로로 생성한다.

**Comment by khw7096** [comment]
이건 이제 어느정도 정리되었는데 닫을까요?

**Comment by baesy0** [comment]
넹! 닫겠습니다
