### ISSUE TITLE
데이터를 tmp에 업로드 후 DB로 복사 vs DB에 바로 업로드

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#321]

**Comment by khw7096** [comment]
파일을 이동하는데 시간이 걸린다. 바로 업로드에 한표.

실패시 삭제를 하는것도 ObjectID 값을 통해 유추가 가능하다.

**Comment by baesy0** [comment]
objectID를 넘겨주기 위해서 addmaya-process와 addmaya페이지의 순서를 바꾼다
