### ISSUE TITLE
vfs(버츄얼 파일 시스템) 셋팅

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#33]
- 웹에서 사용하는 에셋(html, css, javascript, web 서드파트 library)이 바이너리 파일로 내장되면 배포, 개발, 테스트가 쉬워진다.

**Comment by khw7096** [comment]
VFS PR이 올라가야... .html 작업이 분산되겠네요 :-)

**Comment by baesy0** [comment]
c2c3430f29f40d2db2295b0410e8d127fd8da8f2
