### ISSUE TITLE
파일을 업로드할 때 에러가 있다.

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#340]
<img width="618" alt="image" src="https://user-images.githubusercontent.com/1149996/76199004-6627e980-6232-11ea-8d86-b9176e692cc4.png">

**Comment by baesy0** [comment]
로컬에서 실행시킬 땐 잘 돌아가고, 데모페이지에서 하면 저도 동일한 에러가 떠요.
소유권 설정의 문제가 아닐까 싶어요

**Comment by khw7096** [comment]
ㅇㅇ

**Comment by baesy0** [comment]
그럼 이건 lazypic 서버쪽의 소유권을 조절해봐야 하는거죠?

**Comment by khw7096** [comment]
네~ 일단 아직 admin 설정으로 폴더가 만들어지고 있지 않으니... 이후에 admin 값을 바꾸어가면서 해봐요.

**Comment by khw7096** [comment]
일단 서버쪽은 sudo 로 서비스를 다시 실행했어요.

```bash
$ sudo dotori -http :8089 &
```

**Comment by khw7096** [comment]
admin 값으로 나중에 사용되면 문제가 없으니.. 이 이슈는 일단 닫죠.
