### ISSUE TITLE
signin 페이지가 index로 define되어 있음

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#347]
signin 페이지가 index라는 이름으로 define되어 있어서  도토리를 실행시키자마자 signin페이지로 연결돼요
```html
{{define "index"}}
```
아직 로그인 시스템이 완성된 게 아니라서 이 구조는 테스트가 힘들 거 같아요.
그리고 같은 이름으로 두 개의 파일을 define할 수 있는건가요 😮

**Comment by khw7096** [comment]
아니요 오타일듯해요.
