### ISSUE TITLE
process:process중에 에러가 나면 log에 남도록 하기

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#370]

**Comment by baesy0** [comment]
로그가 어떤 식으로 남는게 도움이 될까

**Comment by baesy0** [comment]
https://github.com/digital-idea/dilog/blob/master/dilog.go

dilog와 log 자료구조를 동일하게 짜면 dilog를 그대로 이용할 수도 있겠다

**Comment by baesy0** [comment]
dilog는 커서 연산할 때 비용을 키울 수 있다

**Comment by baesy0** [comment]
log를 남기는 건 별도의 함수로 빼두기

**Comment by baesy0** [comment]
- log 패키지로 시스템에 뿌리기
- SetLog함수로 자료구조에 쌓아두기

둘 다 한다.

**Comment by khw7096** [comment]
#612 이슈로 처리하기. 이 이슈는 닫습니다.

**Comment by baesy0** [comment]
dilog의 목적: 회사 전체의 로그 시스템을 다루고자함
가장 효율적인 상태: 로그 시스템이 아무것도 없고, dilog로 통합될 때
