### ISSUE TITLE
admin setting 에러처리 추가하기

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#375]
형식에 맞지 않는 값을 넣어도 DB에 들어감
<img width="577" alt="image" src="https://user-images.githubusercontent.com/40417084/77131771-31245e00-6aa0-11ea-9328-06226da6e70a.png">
<img width="982" alt="image" src="https://user-images.githubusercontent.com/40417084/77131789-4ac5a580-6aa0-11ea-83a5-c235eca1b3b9.png">

**Comment by khw7096** [comment]
숫자로 구성된 문자열을 체크하는 레귤러 익스프레션을 만들어야겠네요.

이유는 DB에 숫자로 변환되면 안되거든요. 775 일 때 앞 0775 라는 값이 굉장히 중요하더라구요. 안그러면 권한이 달라졌어요.

**Comment by baesy0** [comment]
옥께이👌
