### ISSUE TITLE
upload 방법 토의

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#390]
현재는 업로드 부분과 파일의 정보를 적는 부분이 한 페이지에 있다. 이로서 생기는 단점
- objectID가 생성되는 시점은 사용자가 페이지에 접근할 때 이다.
- upload를 담당하는 dropbox 부분에 대해서는 경로를 수동으로 작성해야한다.
- 업로드가 성공되었더라로 해당 상태를 알거나 기록할 수 없다. 아직 DB에 item이  생성되기 전이기 때문이다.
- 지금 구조에서 DB에 item이 생성되는 시점은 정보를 채운시점이다.

> 제안: 에셋관련된 정보를 먼저 타이핑하고, 이후 파일을 업로드한다. 페이지를 다시 2개로 나누되, 정보를 먼저 입력하고, 이후 파일을 업로드한다. 그렇게 되면 파일 업로드 상태도 체크할 수 있다.(예) thumbnail uploaded, thumbnail mov uploaded, data uploaded) 같은것.

**Comment by baesy0** [comment]
페이지를 분리한다.
DB에 item을 생성 후, 파일을 업로드한다.
