### ISSUE TITLE
blender로 mov만드는 방법. usd, abc 뽑는 방법 공유

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#397]
thanks to 윤지은, the master of blender
## mov
<img width="238" alt="스크린샷 2020-03-26 오전 1 11 10" src="https://user-images.githubusercontent.com/40417084/77560376-bd9baa00-6f00-11ea-9c6e-6d53946cacbd.png">

- 테스트 데이터이기 때문에 가벼워야 한다.
- 작은 사이즈의 resolution은 보통 x:640 y:480
- Frame start, end로 길이 조절. 짧게 1과 10으로 설정.
- Output: 저장경로

<img width="249" alt="스크린샷 2020-03-26 오전 1 11 42" src="https://user-images.githubusercontent.com/40417084/77560892-57fbed80-6f01-11ea-94a8-0f39dc0e1603.png">

- File format: ffmpeg
- Container: Quicktime
이렇게 해야 mov가 나옴!

<img width="308" alt="스크린샷 2020-03-26 오전 1 12 47" src="https://user-images.githubusercontent.com/40417084/77561176-b6c16700-6f01-11ea-9b32-d2a45f399de8.png">

세팅 다했으면 메뉴의 Render > Render Animation

**Comment by baesy0** [comment]
## USD / ABC
<img width="542" alt="image" src="https://user-images.githubusercontent.com/40417084/77561348-ef614080-6f01-11ea-8c3b-12d02dbbfe19.png">
File > Export > Universal Scene Description
File > Export > Alembic

**Comment by khw7096** [comment]
thank you for bailey and yoonji~
