### ISSUE TITLE
경로 관련 함수 리턴값 형태 통일하기

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#403]
현재 경로를 리턴하는 함수는 idToPath, GetRootPath 2개가 있어요.
어떤 함수는 뒤에 슬래시가 붙은 경로를, 어떤 함수는 슬래시가 붙지 않은 경로를 리턴해요.
통일시키면 좋을 거 같아서요

### 경로관련 함수
- idToPath
    - 리턴값의 형태: 54/75/9e/b3/c090d8/3494/e2/d8/04
- GetRootPath
    - 리턴값의 형태: dotori/

**Comment by khw7096** [comment]
```
54/75/9e/b3/c090d8/3494/e2/d8/04
를
/54/75/9e/b3/c090d8/3494/e2/d8/04/
위처럼 바꾸면 활용도가 더 좋을듯하네요.
```
