### ISSUE TITLE
meta:mgo에서 mongo-go-driver로 전환하기 

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#409]
mgo
- 비공식 라이브러리
- 개발이 중단됨

mongo-go-driver
- 공식 라이브러리
- mongoDB측에서 관리

**Comment by baesy0** [comment]
1. mongo-go-driver 테스트
    따로 레포지터리를 만들어서 테스트를 해본다.
    - DB연결
    - item 찾기
    - item 삽입
    ...등등
1. 기존 코드에 적용
    함수 하나씩 테스트해본면서 바꿔본다.

**Comment by khw7096** [comment]
관련함수 총 17개

**Comment by baesy0** [comment]
## 관련 이슈
#412

**Comment by khw7096** [comment]
전환 완료. 세부적인 에러처리가 남았다.
