### ISSUE TITLE
context의 쓰임에 대해서 알아보기

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#431]
- Context는 무엇인가
- MongoDB는 왜 Context를 사용하는가

**Comment by baesy0** [comment]
<img width="720" alt="image" src="https://user-images.githubusercontent.com/40417084/78453823-3a800e00-76cf-11ea-8008-fa5a30003dbc.png">
https://jaehue.github.io/post/how-to-use-golang-context/

**Comment by khw7096** [comment]
https://www.joinc.co.kr/w/man/12/golang/context

**Comment by baesy0** [comment]
```
./http_restapi.go:159:8: the cancel function returned by context.WithTimeout should be called, not discarded, to avoid a context leak
```

**Comment by baesy0** [comment]
kakao에서 Golang으로 진행중인 프로젝트 중 context가 쓰인 부분
https://github.com/kakao/MRTE2/blob/8eeadb5d9aba4d7935c55f40cdf77aa7f48e81fc/MRTECollector/src/github.com/go-sql-driver/mysql/connection_go18.go#L20
