### ISSUE TITLE
GitHub Actions 사용 건의

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#466]
repository에서 바로 탭으로 접근가능해서 travisCI보다 편할 것 같아요.

**Comment by khw7096** [comment]
좋습니다. TravisCI 보다 편합니다.

**Comment by baesy0** [comment]
옥께이 진행하겠슴다

**Comment by ChaeyunBae** [comment]
<img width="1236" alt="스크린샷 2020-04-06 오후 4 06 56" src="https://user-images.githubusercontent.com/46209590/78531594-af169200-7820-11ea-8b99-b6d9aea4ecbf.png">
PR 옆에 다 X 뜨는 거 이거랑 관련있는 건가요???

**Comment by khw7096** [comment]
위 에 X 뜨는건 DB 마이그레이션을 진행할 때 무시하고 머징해서 그래요. 지금은 X 가 뜨지 않아요.

**Comment by khw7096** [comment]
Action에서 빌드가 잘 되고 있군요. 이슈를 닫을께요. 이제는 사용하면서 문제가 생겼을 때 이슈를 다시 여는 방식이 좋을듯해요.
