### ISSUE TITLE
DB Migration 완료 기념

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#474]
![E3D7115A-ECFF-4CC2-8A87-8903049CFBAB](https://user-images.githubusercontent.com/40417084/78674818-27fc1380-791f-11ea-9eeb-2dacf6c45879.jpeg)

**Comment by khw7096** [comment]
ㅋㅋㅋㅋㅋ

**Comment by ChaeyunBae** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ
