### ISSUE TITLE
서버용량체크:프로세스 페이지에 용량 그래프 추가하기

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#478]

**Comment by baesy0** [comment]
~80%
~85%
~90%
색깔을 다르게 지정하기

**Comment by 78963l** [comment]
linux에서 df로 보는 결과와 약간의 오차는 있습니다.

**Comment by khw7096** [comment]
각 OS마다 조금씩 달라요. 파일시스템마다 각 파일을 저장하는 정보를 담는 바이트가 다르기 때문이예요. 정상이랍니다.
