### ISSUE TITLE
로고만들기

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#48]

**Comment by baesy0** [comment]
도토리 모양 귀여울 거 같아요

**Comment by baesy0** [comment]
벡터타입으로

**Comment by khw7096** [comment]
![IMG_0574](https://user-images.githubusercontent.com/1149996/69252327-2b079900-0bf6-11ea-9ff6-a947108fad6e.jpeg)

어때요? 지인이 대충 그린!!

**Comment by baesy0** [comment]
ㅋㅋㅋㅋㅋ정말 대충 그린ㅋㅋㅋ

**Comment by 78963l** [comment]
![8CDA154E-EC71-4F86-AB38-48F5EFD61712](https://user-images.githubusercontent.com/46780796/70594580-5cd3b480-1c24-11ea-9d12-3db06f952b4a.png)

**Comment by baesy0** [comment]
로고가 사용되는 경우
- 모바일 아이콘
- 웹 아이콘
- 굿즈(S2)

**Comment by baesy0** [comment]
성민님 도토리 무서워여...

**Comment by khw7096** [comment]
연휴기간중 로고 컨테스트

**Comment by baesy0** [comment]
## 로고 컨테스트 - 후보 1
- 동글동글한 느낌으로 만들어봤어요
- 로고도 동글동글하면 좋겠다싶어서 손으로 써봤습니다
- 귀엽지 않나요?
- 픽미픽미픽미업
<img width="285" alt="image" src="https://user-images.githubusercontent.com/40417084/71448701-93601200-2782-11ea-841b-b2a49dd449c5.png">

**Comment by baesy0** [comment]
### 매력 포인트 1
다양하고 귀여운 버전이 있습니다
<img width="235" alt="image" src="https://user-images.githubusercontent.com/40417084/71448732-0c5f6980-2783-11ea-813a-85d8b2666d8d.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/40417084/71448741-2b5dfb80-2783-11ea-9338-bab0aee4c9f1.png">

**Comment by baesy0** [comment]
### 매력 포인트 2
글자만 필요한 경우도 준비되어 있습니다
<img width="444" alt="image" src="https://user-images.githubusercontent.com/40417084/71448752-8859b180-2783-11ea-8dbf-b629d03b4b0d.png">
<img width="444" alt="image" src="https://user-images.githubusercontent.com/40417084/71448766-b0e1ab80-2783-11ea-81bd-61c3ed9553d4.png">

**Comment by ChaeyunBae** [comment]
넘 귀엽읍니다,,, +2

**Comment by baesy0** [comment]
감사합니다 프로듀서님! 더욱 노력하는 도토리되겠읍니다!
ㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by khw7096** [comment]
일단 귀엽습니다. 다른분들도~ 기다려보죠.

**Comment by sar9702** [comment]
왘ㅋㅋ너무 귀여운데요ㅠㅠ

**Comment by khw7096** [comment]
![image](https://user-images.githubusercontent.com/1149996/71559519-76894e80-2aa2-11ea-9c9e-db90419651d8.png)

**Comment by khw7096** [comment]
![image](https://user-images.githubusercontent.com/1149996/71637387-afcde400-2c85-11ea-9b21-b51864579ca0.png)

**Comment by baesy0** [comment]
어얼 이건 좀 인정

**Comment by 78963l** [comment]
![ewrewrewr](https://user-images.githubusercontent.com/46780796/71662203-fd387700-2d93-11ea-8de1-66249dfd90c0.PNG)

**Comment by 78963l** [comment]
![qweqwe](https://user-images.githubusercontent.com/46780796/71662557-3d4c2980-2d95-11ea-84f6-7e98a1c5991b.PNG)

**Comment by 78963l** [comment]
![ewrewrewr](https://user-images.githubusercontent.com/46780796/71662612-72f11280-2d95-11ea-919b-37b6e5515698.PNG)

**Comment by kybin** [comment]
우주가 느껴지네요 ㅋㅋㅋ

**Comment by 78963l** [comment]
![werewrewr](https://user-images.githubusercontent.com/46780796/71668214-56f86b80-2dab-11ea-882a-7ed72bd4fb17.PNG)

**Comment by 78963l** [comment]
전 미적감각이 제로인것같아요..ㅎ

**Comment by baesy0** [comment]
도토리와 다람쥐의 혼종이다ㅋㅋㅋ

**Comment by khw7096** [comment]
코피도 나...

**Comment by ChaeyunBae** [comment]
![dotori_logo_v006 png](https://user-images.githubusercontent.com/46209590/71910481-54d04b80-31b5-11ea-9656-9dd1d35fc42c.png)

**Comment by kybin** [comment]
예쁘네요!

**Comment by khw7096** [comment]
오늘은 투표를 통해 1차 로고를 선정하고 등록, 더 좋은 로고가 제안될 때 바꾸는걸로 해용~~

**Comment by baesy0** [comment]
오 채윤님 로고는 티셔츠 굿즈를 만든다면 잘 어울리겠군..

**Comment by khw7096** [comment]
#124 이슈로 1차 Close 하고 다시 이슈가 발생할 때 reopen 한다.

**Comment by baesy0** [comment]
https://vectr.com/bailey0/adpMyZFva.svg?width=368&height=368&select=adpMyZFvapage0

**Comment by khw7096** [comment]
오호~! 이걸로 올려줘야 겠군요.
