### ISSUE TITLE
바뀐 status가 templatefunc에 적용되도록 하기

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#492]
현재는 status가 바뀌면 templatefunc.go의 Int2Status를 수작업으로 바꿔줘야 한다.

**Comment by khw7096** [comment]
처음부터 status를 문자로 사용하는것도 고민해봐야한다.
이유는 미래에 각 포멧별로 어떤 상태가 추가될 지 예측할 수 없기 때문이다.
한 예로, .usd 포멧의 축을 y 에서 z 로 바꾸어야 하는 상태를 추가한다면, status 넘버가 뒤로 계속 밀린다.
