### ISSUE TITLE
addmaya-item에서 addmaya-file로 이동 후 뒤로가기해서 NEXT버튼을 누르면 에러가 발생함

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#493]
동일한 objectID로 문서를 생성하려고 하기 때문에 생기는 에러

**Comment by khw7096** [comment]
에러나는 경우 그 경우에 다시 리다이렉트 하고, DB를 클린업 하는 형태로 처리.

**Comment by baesy0** [comment]
<img width="638" alt="image" src="https://user-images.githubusercontent.com/40417084/82039318-cb3f0600-96df-11ea-8556-ff7de56881fb.png">

**Comment by baesy0** [comment]
```go
fmt.Printf("%T", err)
```
```
mongo.WriteException
```

**Comment by baesy0** [comment]
https://github.com/mongodb/mongo-go-driver/search?q=duplicate+key+error+collection&unscoped_q=duplicate+key+error+collection

**Comment by baesy0** [comment]
https://github.com/mongodb/mongo-go-driver/blob/c814cfb676dc29a6ad6171e138510ee88c51983f/mongo/integration/collection_test.go#L27

**Comment by khw7096** [comment]
에러코드가 11000이면 이라는 문장을 작성해야 한다.

**Comment by baesy0** [comment]
https://github.com/mongodb/mongo-go-driver/blob/c335d0ce4c36997dc5a85083f163ecf4f1af3f48/mongo/errors.go#L190

**Comment by khw7096** [comment]
<img width="612" alt="image" src="https://user-images.githubusercontent.com/1149996/82046286-933dc000-96eb-11ea-909c-12c46647bd29.png">

가이드 코드
