### ISSUE TITLE
가입 후 로그인시 문제

### ISSUE THREAD

**Issue by 78963l** [RD101/dotori#495]
가입 후에 로그인 했을때 mongo: no documents in result 가 나오는 현상
어떻게 해야할까요..?

**Comment by khw7096** [comment]
전에 있던 DB를 날려요~ 자료구조가 바뀌어서 그래요.

**Comment by khw7096** [comment]
```bash
$ mongo

use dotori
db.maya.drop()
```

**Comment by khw7096** [comment]
아직도 막힌다면, hangout 또는 zoom 으로 봐줄께요~! teamviewer도 좋아요.

**Comment by khw7096** [comment]
이 문제는 해결됨.
