### ISSUE TITLE
Item tags 리스트에 중복되는 항목이 있으면 삭제하는 함수를 만드는 건 어떨까요??

### ISSUE THREAD

**Issue by ChaeyunBae** [RD101/dotori#496]
https://github.com/ChaeyunBae/dotori/commit/68f787f4865b7e0f34cc8e9b6589852186f06957
 
dropzone에 올린 파일 이름들 태그에  append하는 기능 추가 중인데요.
링크 보시면 stringfunc.go의 PathToTags 함수에서 중복체크를 하고 있어요. 그런데 이런 식으로 체크하고 handleUploadMayaFile 함수로 넘기면 한 파일이름에 대한 리스트 중에서만 중복체크가 돼서요!
어차피 tags 칸에 유저가 실수로 같은 단어를 넣었을 경우도 생각해야하는데 그냥 tags에 몽땅 다 때려넣고 중복되면 삭제하는 식으로 하면 어떨까요?? 비효율적까요??

**Comment by khw7096** [comment]
중복이 제거되는 기능이 함수안에 있는게 좋다고 생각해요.

**Comment by ChaeyunBae** [comment]
handleUploadMayaFile 안에서요?!

**Comment by ChaeyunBae** [comment]
#497
