### ISSUE TITLE
process: 썸네일 폴더를 만드는 상태 추가

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#503]

**Comment by khw7096** [comment]
썸네일 이미지를 생성하기 전에 thumbnail 폴더가 먼저 생성되어야 한다.
이 경로에는 이미지를 포함하여, 동영상이 들어가기 때문에 과정이 정확해야한다.

**Comment by baesy0** [comment]
- creatingThumbDir
- createdThumbDir
