### ISSUE TITLE
삭제: 아이템 삭제시에는 재귀로 폴더내부를 체크하면서 삭제되어야 한다.

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#528]
/dotori/5e/99/bb/43/3e76c0/aa5d/c4/71/34/{data, originalthumbimg, orginalthumbmov, thumbnail}
데이터가 있을때 

/dotori/5e/99/bb/43/3e76c0/aa5d/c4/71/34 를 삭제한다.(필수!)
/dotori/5e/99/bb/43/3e76c0/aa5d/c4/71 폴더를 검색한다. 만약 해당 폴더에 하위가 없다면 삭제한다.
/dotori/5e/99/bb/43/3e76c0/aa5d/c4 폴더를 검색한다. 만약 해당 폴더에 하위가 없다면 삭제한다.
/dotori/5e/99/bb/43/3e76c0/aa5d 폴더를 검색한다. 만약 해당 폴더에 하위가 없다면 삭제한다.
/dotori/5e/99/bb/43/3e76c0 폴더를 검색한다. 만약 해당 폴더에 하위가 없다면 삭제한다.
/dotori/5e/99/bb/43 폴더를 검색한다. 만약 해당 폴더에 하위가 없다면 삭제한다.
/dotori/5e/99/bb 폴더를 검색한다. 만약 해당 폴더에 하위가 없다면 삭제한다.
/dotori/5e/99 폴더를 검색한다. 만약 해당 폴더에 하위가 없다면 삭제한다.
/dotori/5e 폴더를 검색한다. 만약 해당 폴더에 하위가 없다면 삭제한다.

**Comment by ChaeyunBae** [comment]
```go
func IsEmpty(name string) (bool, error) {
    f, err := os.Open(name)
    if err != nil {
        return false, err
    }
    defer f.Close()

    _, err = f.Readdirnames(1) // Or f.Readdir(1)
    if err == io.EOF {
        return true, nil
    }
    return false, err // Either not empty or error, suits both cases
}
```

https://stackoverflow.com/questions/30697324/how-to-check-if-directory-on-path-is-empty
https://socketloop.com/tutorials/golang-determine-if-directory-is-empty-with-os-file-readdir-function
