### ISSUE TITLE
Process: 연산중인 아이템의 개수를 구하는 DB함수 제작

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#534]

**Comment by khw7096** [comment]
찾아야 하는 갯수는 Ready와 Done이 아닌 것

**Comment by khw7096** [comment]
현재 연산중인 갯수와 인수로 잡은 processnum 을 비교하기위해 사용될 예정이다.

**Comment by khw7096** [comment]
참고코드: https://stackoverflow.com/questions/54876209/find-all-documents-in-a-collection-with-mongo-go-driver

**Comment by baesy0** [comment]
https://stackoverflow.com/questions/26932298/mongodb-in-go-golang-with-mgo-how-to-use-logical-operators-to-query
