### ISSUE TITLE
무의미한 데이터를 삭제할 필요가 있음

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#563]
현재 파일업로드의 구조 상 실제 데이터는 존재하지 않으면서 DB에 정보만 존재하는 경우가 생길 수 있다.
#416 에서는 무의미한 데이터가 발생할 가능성을 줄이는 방향으로 진행이 되었다.
주기적으로 검사해서 무의미한 데이터를 지워줄 필요가 있다.

**Comment by baesy0** [comment]
```go
if !(ThumbImgUploaded || ThumbClipUploaded || DataUploaded) {
    // 데이터가 삭제되어야 한다.
}
```

**Comment by khw7096** [comment]
이건 수동으로 지우는것이 더 좋을 수도 있을거라는 생각을 했어요.
파일 삭제를 자동으로 진행하면, 파일을 업로드하기 위해서 파일을 고르는 시간이 길어질 때 지워질 수도 있으니까요.

공지를 하고 관리자에 의해서 진행되는것이 좋다고 생각은 들어요.

**Comment by baesy0** [comment]
그러면 일단 함수만 만들어놓고 실행시점을 따로 토론하는 건 어때요?

**Comment by baesy0** [comment]
생각이 공유되었으니 이 이슈는 닫을게요!
