### ISSUE TITLE
파일을 한번 Upload하고(드레그하고) 또 드레그하면 에러가 발생한다.

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#567]

**Comment by baesy0** [comment]
.ma .mb는 똑같은 파일을 두 번 올려도 에러가 나지 않는다
![image](https://user-images.githubusercontent.com/40417084/80801078-4257a300-8be6-11ea-84a1-d0db9c15ca86.png)

**Comment by baesy0** [comment]
.jpg .mov는 두 번째 파일부터 에러가 난다
![image](https://user-images.githubusercontent.com/40417084/80801143-6fa45100-8be6-11ea-8c55-f1a081d719b1.png)
![image](https://user-images.githubusercontent.com/40417084/80801150-77fc8c00-8be6-11ea-9871-e6f9ea1f4420.png)

**Comment by baesy0** [comment]
https://github.com/RD101/dotori/blob/master/http_add.go#L448
파일이 업로드될 때 자료구조의 input경로가 path + filename으로 바뀐다.
```go
item.InputThumbnailImgPath = path + f.Filename
```
그래서 두 번째 부터는 에러가 남.

**Comment by baesy0** [comment]
https://github.com/RD101/dotori/blob/ec55ce498ed28d8ff4623aa8ccfcea5d848ae089/process.go#L212
input 경로를 바꿨던 이유.
썸네일 이미지, 클립을 만들 때 바로 가져다 쓰려고

**Comment by baesy0** [comment]
- 썸네일 이미지, 썸네일 동영상은 하나만 필요함
- 두 번째 업로드 시도하는 썸네일은 에러남
- 다시 업로드하면 덮어쓰기 되어야하지 않을까

**Comment by khw7096** [comment]
ID가 같다면, 덮어쓰기 좋습니다.
