### ISSUE TITLE
processingItem 에서는 return 대신 err를 만나면 log.Println 으로 출력되어야 한다.

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#580]

**Comment by khw7096** [comment]
<img width="277" alt="image" src="https://user-images.githubusercontent.com/1149996/80185741-cf7b8480-8647-11ea-94f5-1c69f515df52.png">

코드의 흐름상 이 느낌이 되어야 할 듯하다.

**Comment by baesy0** [comment]
https://stackoverflow.com/questions/29721449/how-can-i-print-to-stderr-in-go-without-using-log

그런데 에러 내용이 stderr에 기록이 되어야 하니 위 링크의 자료를 보고 코드를 짜면 더 좋을 듯해요
