### ISSUE TITLE
processItem에서 *flagDebug 제거하기

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#582]

**Comment by khw7096** [comment]
setlog 함수로 대체한다.

**Comment by baesy0** [comment]
err = SetLog(client, item.ItemType, item.ID.Hex(), "genThumbMp4Container 완료")
	if err != nil {
		return
	}

**Comment by baesy0** [comment]
https://stackoverflow.com/questions/29721449/how-can-i-print-to-stderr-in-go-without-using-log

그런데 에러 내용이 stderr에 기록이 되어야 하니 위 링크의 자료를 보고 코드를 짜면 더 좋을 듯해요.
