### ISSUE TITLE
restapi: 에셋 등록하기

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#597]

**Comment by khw7096** [comment]
curl에서 -F 옵션을 사용하면 파일을 전송할 수 있다.

https://stackoverflow.com/questions/12667797/using-curl-to-upload-post-data-with-files

**Comment by khw7096** [comment]
Go에서 처리하는 방법

https://tutorialedge.net/golang/go-file-upload-tutorial/

**Comment by baesy0** [comment]
필요한 요소
- itemtype
- tag
- attribute
- author
- description
- (...)
