### ISSUE TITLE
무의미한 데이터 삭제 시점 정하기

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#599]
이건 수동으로 지우는것이 더 좋을 수도 있을거라는 생각을 했어요.
파일 삭제를 자동으로 진행하면, 파일을 업로드하기 위해서 파일을 고르는 시간이 길어질 때 지워질 수도 있으니까요.

공지를 하고 관리자에 의해서 진행되는것이 좋다고 생각은 들어요.

_Originally posted by @khw7096 in https://github.com/RD101/dotori/issues/563#issuecomment-618825874_

**Comment by baesy0** [comment]
https://github.com/RD101/dotori/issues/600#issuecomment-620450824

<img width="386" alt="image" src="https://user-images.githubusercontent.com/40417084/80465354-05857500-8976-11ea-9395-90b686a69011.png">

**Comment by khw7096** [comment]
수동으로 삭제하기.
