### ISSUE TITLE
id를 이용해서 디렉토리 분리하기

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#60]
한폴더에 파일이 몰리면 디렉토리 로딩시 문제가 크게 발생한다.

**Comment by baesy0** [comment]
효율적인 방법에 대한 토론이 필요하다

**Comment by baesy0** [comment]
mongoDB ID를 사용하는 경우
2개씩 자르면 depth가 12
3개씩 자르면 depth가 8
4개씩 자르면 depth가 6
이 나온다.

**Comment by ChaeyunBae** [comment]
mongoDB 이용
- ex) id split 기준(2?3?)
- 12 : 5d/c5/42/18/f4/8b/e7/c6/8c/be/82/5d
- 8 :  5dc/542/18f/48b/e7c/68c/be8/25d
- 6 : 5dc5/4218/f48b/e7c6/8cbe/825d

**Comment by baesy0** [comment]
id가 의미하는 바가 있으면 살리는 방향으로 자르기

**Comment by khw7096** [comment]
mongoDB id mean: https://mongodb.github.io/node-mongodb-native/2.0/tutorials/objectid/

**Comment by khw7096** [comment]
"54759eb3c090d83494e2d804"
Size | Description
-- | --
4 bytes | a 4-byte value representing the seconds since the Unix epoch
3 bytes | a 3-byte machine identifier
2 bytes | 2-byte process id
3 bytes | 3-byte counter, starting with a random value

**Comment by khw7096** [comment]
결정: 54/75/9e/b3/c090d8/3494/e2/d8/04

**Comment by baesy0** [comment]
이유
- 더 많은 상황을 포괄할 수 있다. = 혹시 프로세스id나 머신을 확인해야하는 상황이 생겼을 때 이용할 수 있다

**Comment by 78963l** [comment]
id를 생성하는 것과 id를 분리하여 디렉토리를 만드는것은 어떤 스크립트에 추가하는게 좋을까요?

**Comment by 78963l** [comment]
https://github.com/coolbed/mgo-oid

**Comment by baesy0** [comment]
id는 데이터가 DB에 들어갈 때 자동으로 생성되는 object id를 사용할거라서 생성할 필요없어요:)

**Comment by khw7096** [comment]
경로를 만드는 것이니 pathfunc.go 를 만들어서 입력해주세요.
