### ISSUE TITLE
meta: 무의미한 데이터를 삭제하는 함수 만들기

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#600]

**Comment by baesy0** [comment]
```go
if !(ThumbImgUploaded || ThumbClipUploaded || DataUploaded) {
    // 데이터가 삭제되어야 한다.
}
```

- 데이터는 있는데 썸네일 이미지나 썸네일 클립이 없을 경우, 지워지는 게 맞을까요?
- 썸네일만 추가되면 좋은 에셋이 될 가능성이 있다면 다른 쪽으로 유도하는 게 낫지 않을까 싶어요

**Comment by baesy0** [comment]
목록을 보여주고, 사용자가 정하게 하는 것도 나을 거 같다.
select|ID|ThumbImg|ThumbClip|Data
:----:|:----:|:----:|:----:|:----:
[ ]|1qa3|x|o|o
[x]|3zv0|o|o|x
[ ]|vzd3|x|x|o

**Comment by baesy0** [comment]
필요한 데이터가 모두 업로드되지 않은 아이템을 가져오는 dbapi를 만들기

**Comment by baesy0** [comment]
필요한 데이터가 모두 업로드 되어 있지 않은 아이템을 보여주는 페이지 필요.
타입별로 필요한 데이터가 다르니까 타입별로 보여주기.
삭제버튼 누르면 체크된 아이템 정보를 날려주기.

**Comment by baesy0** [comment]
page url or 함수이름
- delete item: 너무 범용적이야 나중에 써야 할 거 같아..
- delete trash..? : 어감이 별로..
- clean up DB: 일단 맘에 듬

**Comment by khw7096** [comment]
저도 clean up DB 가 마음에 드네요.

**Comment by baesy0** [comment]
#666
