### ISSUE TITLE
로그처리 -용빈님의 이슈로 토론해보기.

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#621]
![image](https://user-images.githubusercontent.com/1149996/80737669-d24a0e00-8b4e-11ea-9255-5a98444548d8.png)

**Comment by baesy0** [comment]
음.. 동의해요!

**Comment by khw7096** [comment]
go 를 쓰기위해서라고 하니.. 용빈씨도 그냥 지금도 괜찮다고 하여.. 이 이슈를 닫습니다.

**Comment by khw7096** [comment]
채널로 로그를 보내야해요. 그런데 그렇게 구현하면 꽤 복잡해져요.

**Comment by khw7096** [comment]
https://tour.golang.org/concurrency/2
