### ISSUE TITLE
dbapi의 UpdateUsingRate 함수에서 업데이트 되지 않은 usingrate를 리턴하고 있어요!

### ISSUE THREAD

**Issue by sar9702** [RD101/dotori#640]

**Comment by baesy0** [comment]
ㅇㅇ 1만큼 차이나네요. 왜 그런거지..
<img width="702" alt="image" src="https://user-images.githubusercontent.com/40417084/80935920-cfc70d00-8e09-11ea-8e8b-2bb1d3a77536.png">

<img width="964" alt="image" src="https://user-images.githubusercontent.com/40417084/80935938-e79e9100-8e09-11ea-890e-8666b7f3ce15.png">

**Comment by khw7096** [comment]
이 함수는 Get 이예요? Post예요? 만약 Post라면 DB에 업데이트하고 난 후의 값을 json 으로 리턴해야할 것 같아요.

**Comment by baesy0** [comment]
https://stackoverflow.com/questions/32811510/mongoose-findoneandupdate-doesnt-return-updated-document

**Comment by baesy0** [comment]
https://github.com/mongodb/mongo-go-driver/blob/master/mongo/options/findoptions.go#L680

https://godoc.org/go.mongodb.org/mongo-driver/mongo/options#ReturnDocument

**Comment by baesy0** [comment]
update후의 document를 리턴하는 옵션은 4,0이후에 추가됨.
centOs에서는 2.x대 mongoDB를 기본적으로 사용.
주석으로 달아놓기
