### ISSUE TITLE
footage: example 올리기

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#646]
- dpx
- exr linear
- exr aces / ACES2065-1

**Comment by ChaeyunBae** [comment]
- RD101에서 사용 중인 color space 뭔지 조사하기

**Comment by khw7096** [comment]
각 샘플 프레임은 5프레임씩 올린다.

예상용량: 총 75메가

**Comment by khw7096** [comment]
75메가가 되어버리면 git clone 시 굉장히 느려진다. 다른 포멧과 다르게 다른 리포지터리에 빼는 방법도 있다.

**Comment by khw7096** [comment]
https://github.com/lazypic/tdcourse/blob/master/docs/sample.md

**Comment by khw7096** [comment]
![image](https://user-images.githubusercontent.com/1149996/81477036-4de34380-9250-11ea-9b4c-ac0b80cd235d.png)

실제로 97메가

**Comment by khw7096** [comment]
https://github.com/lazypic/tdcourse_examples/tree/master/footage

용량이 커서 위 리포지터리에 일단 올려두었다.

**Comment by khw7096** [comment]
용량이 꽤 크니 실제 이 리포지터리에 올리는 것은 같이 토론해봐요.

**Comment by 78963l** [comment]
네넵!

**Comment by baesy0** [comment]
네넹!
