### ISSUE TITLE
nuke: example 올리기

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#705]
- . nk
- .gizmo

정도이지 않을까?

**Comment by khw7096** [comment]
이것도 애림님에게  Assign해도 될까요?

**Comment by sar9702** [comment]
네 그럼요!!

**Comment by sar9702** [comment]
지금 누크 파일 예제가 있는데 기즈모 파일만 추가하면 될까요?

**Comment by khw7096** [comment]
네~ 과정상 라이센스의 문제가 없다면 추가하는 것 좋아요.
