### ISSUE TITLE
최초 안내 페이지 만들기

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#715]
- 최근등록 에셋
- 등록된 태그 보이기

**Comment by baesy0** [comment]
어차피 할 거라면 help페이지에 통합하는 것도 좋을 거 같아요

**Comment by 78963l** [comment]
<img width="1680" alt="스크린샷 2020-05-25 오후 10 49 59" src="https://user-images.githubusercontent.com/46780796/82818760-2809a000-9eda-11ea-81f7-d5c610496cda.png">
혹시 이런거 인가요??

**Comment by khw7096** [comment]
아뇨~ 예를 들면..

**Comment by khw7096** [comment]
![image](https://user-images.githubusercontent.com/1149996/82823071-d82ed700-9ee1-11ea-8b63-ef23b826b1b9.png)

이런느낌~

**Comment by khw7096** [comment]
도토리라고 하는 플렛폼에 접속했을 때 뉴크같은 것이 보통은 안내페이지가 되요~

에픽은 아래와 같은 결이죠~

![image](https://user-images.githubusercontent.com/1149996/82823195-188e5500-9ee2-11ea-8239-8851166d9bf4.png)

스팀은 아래와 같은 결이구요~
![image](https://user-images.githubusercontent.com/1149996/82823227-27750780-9ee2-11ea-8b7d-1c67b900581b.png)

**Comment by khw7096** [comment]
참고로 유니티 에셋 스토어도 올립니다.

![image](https://user-images.githubusercontent.com/1149996/82823738-17115c80-9ee3-11ea-9ea1-9c087fc991c8.png)

**Comment by 78963l** [comment]
아하 이해했습니당!

**Comment by khw7096** [comment]
- 아이디어:  최고의 Author

**Comment by 78963l** [comment]
<img width="1271" alt="스크린샷 2020-05-29 오후 2 37 40" src="https://user-images.githubusercontent.com/46780796/83225122-0817fc00-a1ba-11ea-9239-7427c6548f8e.png">

**Comment by 78963l** [comment]
이런식으로 카테고리가 왼쪽이나 오른쪽에 있었으면 좋겠습니다.

**Comment by 78963l** [comment]
<img width="1088" alt="스크린샷 2020-05-29 오후 3 00 15" src="https://user-images.githubusercontent.com/46780796/83226534-30edc080-a1bd-11ea-9123-d3c6a5e65d4b.png">

**Comment by 78963l** [comment]
sort에는 빈도수 많은 에셋이나 빈도수적은에셋을 오른쪽에 쓰지말고 sort에 넣고, 오름차순, 내림차순 이런것 등등 넣으면 괜찮을것같습니다.

**Comment by khw7096** [comment]
그건 검색바에 넣어야겠군요~!

**Comment by khw7096** [comment]
그건 검색바에 넣어야겠군요~!

**Comment by khw7096** [comment]
참고로 CSI는 아래와 같아요.

<img width="729" alt="image" src="https://user-images.githubusercontent.com/1149996/83238895-0d814080-a1d2-11ea-8055-be06b059f355.png">

**Comment by 78963l** [comment]
아하! 너무조아요

**Comment by 78963l** [comment]
> ![image](https://user-images.githubusercontent.com/1149996/82823071-d82ed700-9ee1-11ea-8b63-ef23b826b1b9.png)
> 
> 이런느낌~

이걸로 픽해보는건 어떤가요?? ㅎㅎ

**Comment by 78963l** [comment]
https://github.com/RD101/dotori/issues/715#issuecomment-635777484

생각해보니깐 오른쪽에 sort느낌은 csi처럼 일단 묶는게 좋을것 같기도 해보여요

**Comment by khw7096** [comment]
시작 포인트로 좋아보입니다. 다른 분들도 의견 남겨주세요. :-)

**Comment by baesy0** [comment]
저도 동의!

**Comment by 78963l** [comment]
의견남겨주시면 시작할께요 ㅎㅎ

**Comment by khw7096** [comment]
삭제 예정인 에셋은 아직 구현하지 않음.
