### ISSUE TITLE
meta: 검색 쿼리 만들기

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#72]

**Comment by ChaeyunBae** [comment]
mongo DB query example 검색해보기

**Comment by ChaeyunBae** [comment]
같이 해주면 안될까요,,,

**Comment by khw7096** [comment]
1. 전체 아이템 가지고 오는 함수짜기.
2. 태그에 들어가 있는 단어 검색하기.
3. 복잡한 검색 짜기.

**Comment by baesy0** [comment]
### 참고 코드
https://github.com/lazypic/kalena/blob/master/dbapi.go - AllSchedules함수
