### ISSUE TITLE
썸네일이 안보여요!

### ISSUE THREAD

**Issue by ChaeyunBae** [RD101/dotori#721]
뭐가 문제인지 잘 모르겠는데 첨부 이미지 좀 봐주시면 감사하겠습니다!
<img width="545" alt="스크린샷 2020-05-20 오후 5 12 17" src="https://user-images.githubusercontent.com/46209590/82422344-4a0bb880-9abd-11ea-808d-8741f4538c3c.png">
<img width="878" alt="스크린샷 2020-05-20 오후 5 12 32" src="https://user-images.githubusercontent.com/46209590/82422359-4d9f3f80-9abd-11ea-857d-4bef68769636.png">
<img width="416" alt="스크린샷 2020-05-20 오후 5 12 47" src="https://user-images.githubusercontent.com/46209590/82422363-4e37d600-9abd-11ea-9846-23862cca7f7f.png">
<img width="451" alt="스크린샷 2020-05-20 오후 5 12 53" src="https://user-images.githubusercontent.com/46209590/82422365-4f690300-9abd-11ea-88dc-7be3d9deb735.png">

**Comment by khw7096** [comment]
원인은 서버에서 찾아봐야 할듯해요. 방문할 때 같이 봐봐요~!

**Comment by khw7096** [comment]
그 사이에 원인을 찾게되면 이유를 적어주거나, 원인을 없앨 수 있는 코드를 PR해주어도 좋아요~

**Comment by ChaeyunBae** [comment]
네엡!

**Comment by khw7096** [comment]
예를 들어서 Maya collection 이외에 다른 콜렉션이 있을 때 그 콜렉션에서 연산할 아이템을 찾을 수 없다면 위와 같은 결과가 나오는 것을 확인했어요.

제안: 아이템을 하나로 모으면 이러한 문제점을 쉽게 해결할 수 있을 것 같아요. 여러분들의 생각은?

**Comment by khw7096** [comment]
다른사람들의 생각은?

**Comment by baesy0** [comment]
저도 동의해요

**Comment by khw7096** [comment]
그럼 진행합니다.

**Comment by baesy0** [comment]
옥께이

**Comment by ChaeyunBae** [comment]
아하 여기서 나온 거였군요

**Comment by ChaeyunBae** [comment]
#735
