### ISSUE TITLE
item 컬렉션을 만들고 통합하기.

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#735]

**Comment by khw7096** [comment]
items

**Comment by ChaeyunBae** [comment]
엇 그럼 maya나 houdini 이런 식으로 itemtype 별로 collection이 들어가는 게 아니라 따로 가나요???

**Comment by khw7096** [comment]
전부 통합되어서 갈것 같아요. 이 수정은 꽤 커서 이번주 데모를 넘기고 개발을 할 것 같아요.~ 수요일에 토론해봐요.

**Comment by khw7096** [comment]
제 이슈가 처리되려면 이 이슈가 진행되어야 해서 진행중이예요.

**Comment by khw7096** [comment]
리뷰올림.
