### ISSUE TITLE
USD: usd 추가 페이지에 usd 관련옵션 추가하기

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#738]

**Comment by khw7096** [comment]
<img width="422" alt="image" src="https://user-images.githubusercontent.com/1149996/82816971-1377d880-9ed7-11ea-8661-0e028248a73d.png">

마야와 다르게 위 타입이 추가되어야 해요.

**Comment by baesy0** [comment]
html로 추가하는건 간단할 거 같은데 정보를 담을 자료구조를 생각해봐야 할 거 같아요!
