### ISSUE TITLE
어트리뷰트에 빈문자열은 예외처리를 해야할까요?

### ISSUE THREAD

**Issue by sar9702** [RD101/dotori#752]
누크 edit 핸들러 추가하면서 발견한건데
편집 페이지에서 어트리뷰트의 + 버튼을 클릭하고 아무것도 입력하지않은 상태에서 업데이트를 하면 아래 사진처럼 되더라구요.

key와 value 둘 중에 하나라도 빈문자열이면 어트리뷰트에 추가가 안되게 해야할까요?

![image](https://user-images.githubusercontent.com/14924389/82881927-4e334c80-9f7b-11ea-9ec3-eb4774ac6b3a.png)

**Comment by baesy0** [comment]
오 네 저는 그렇게하면 좋을 거 같아요👍 
둘 중 하나라도 없으면 의미없기도 하고, 둘 다 빈 문자열이면 안들어가는 게 맞을 거 같구요
