### ISSUE TITLE
meta: 회사 내 캐시 만들어서 놀기

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#758]
캐시 발급해주기(ex: 10rd)
- 업로드 할 때 마다
- 본인이 만든 에셋이 다운로드 될 때 마다

모은 캐시로 상점에서 아이템 구매가능
- 반차 구매
- 연차 구매..

**Comment by kybin** [comment]
회사에서 논다구요?

**Comment by baesy0** [comment]
> 회사에서 논다구요?

같이 노실래요?

**Comment by baesy0** [comment]
나중에 진짜 실행할 때 다시 열어요:D
