### ISSUE TITLE
드래그 해서 올린 파일이 지워지지 않네요

### ISSUE THREAD

**Issue by kybin** [RD101/dotori#762]
![Screenshot_2020-05-27_23-06-23](https://user-images.githubusercontent.com/595519/83030949-f7a73a80-a06e-11ea-8041-3af92f22d84c.png)

허용하지 않는 포맷이라고 해서 X 버튼을 눌러도 해당 파일이 사라지지 않아요.

파이어폭스 버전 76.0.1 (64-bit) 입니다.

**Comment by baesy0** [comment]
dropzone은 가져다 쓴 라이브러리인데요 
에러가 났음을 알려주는 X 이고, 따로 기능은 없는 거 같아요

**Comment by kybin** [comment]
아, 그런 X인가요... 드롭존이 잘못했네요 ㅋ

그럼 버그가 아니므로 닫을게요.
