### ISSUE TITLE
이미지 등록 절차가 완료되지 않음

### ISSUE THREAD

**Issue by kybin** [RD101/dotori#763]
addmaya-file 페이지에 작은 jpg 파일을 업로드 해 보았는데 "썸네일클립을 업로드해주세요" 문자열이 뜨면서 더이상 진행되지 않아요. 무엇 때문일까요?

**Comment by khw7096** [comment]
썸네일, 파일, 동영상 총 3개를 같이 올려야 등록이 되어요.

**Comment by khw7096** [comment]
안내문을 좀더 친절하게 바꾸어야겠네요~!

**Comment by baesy0** [comment]
구체적인 이슈를 새로 만들었어요
