### ISSUE TITLE
몇몇 페이지에서 도토리 로고가 표시되지 않음

### ISSUE THREAD

**Issue by kybin** [RD101/dotori#764]
후디니, 블렌더, 알렘빅 추가 페이지에서 도토리 로고가 표시되지 않습니다.

**Comment by khw7096** [comment]
아직 그곳은 미지의 땅이예요~

![image](https://user-images.githubusercontent.com/1149996/83042570-c170b780-a07c-11ea-90c5-bbf06f3176ca.png)

**Comment by khw7096** [comment]
아직 그곳은 미지의 땅이랍니다.

![image](https://user-images.githubusercontent.com/1149996/83042712-ed8c3880-a07c-11ea-9ed6-cc4b43dacf44.png)

**Comment by baesy0** [comment]
진행중이니까 닫을게요!
