### ISSUE TITLE
테스트서버가 https 프로토콜이 아님

### ISSUE THREAD

**Issue by kybin** [RD101/dotori#765]
테스트 서버가 인터넷상에 존재하지만 https 프로토콜이 아닙니다.
이는 모든 사이트에 같은 아이디와 패스워드를 쓰는 분들에게는 치명적일 수 있습니다.
http 프로토콜로 아이디와 패스워드를 생성하면 그 정보가 인터넷에 노출되게 되니까요.

**Comment by khw7096** [comment]
이미 해당 서버는 인증서를 서비스 2개에 사용중이긴해요.
443 포트가 아니어도 인증서를 사용할 수 있도록 해야겠군요~!
