### ISSUE TITLE
GOBIN 에러 없애기

### ISSUE THREAD

**Issue by ChaeyunBae** [RD101/dotori#80]

**Comment by 78963l** [comment]
window 환경변수 셋팅입니다.

**Comment by khw7096** [comment]
go1.13 버전을 사용하고, PR중 go.mod, go.sum 을 머지하면 gopath 없이 사용할 수 있어요.

**Comment by khw7096** [comment]
GOPATH는 없어지는 추세예요.

**Comment by khw7096** [comment]
심바님은 Go 버전이 몇 인가요?

**Comment by khw7096** [comment]
결론:

Go1.13을 사용할 것.
git pull upstream master 할것

**Comment by baesy0** [comment]
👌 오케이

**Comment by 78963l** [comment]
> 심바님은 Go 버전이 몇 인가요?

제..제가 포멧을 해서 하하

**Comment by khw7096** [comment]
포멧 이후 해결은 되었나요?

**Comment by khw7096** [comment]
이 이슈는 잠잠하니 닫을께요. 다시 비슷한 이슈가 발생하면 reopen 합니다.
