### ISSUE TITLE
GO BIN 설정

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#803]

**Comment by baesy0** [comment]
README에 방법 적기

**Comment by 78963l** [comment]
#!/bin/sh
go run assets/asset_generate.go
go install
go build
./dotori -debug -http :80

**Comment by baesy0** [comment]
```bash
#!/bin/sh
go run assets/asset_generate.go
go build
./dotori -debug -http :80
```

**Comment by baesy0** [comment]
질문
- go build 하면 dotori가 생성되는 경로는?

**Comment by 78963l** [comment]
mac

export GOBIN=$HOME/bin
export PATH=$PATH:$GOBIN

**Comment by khw7096** [comment]
https://github.com/lazypic/init/blob/master/init.bash#L9

에 적혀있는 그대로 이군요~!
개발환경 셋팅이라는 문건으로 작성해둘께요.
