### ISSUE TITLE
썸네일 디자인

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#806]
1. 자료구조 보면서 들어가야할 정보 고르기
1. 정보 배치하기

**Comment by ChaeyunBae** [comment]
#179

**Comment by ChaeyunBae** [comment]
- Title
- Tags
- Using Rate

**Comment by ChaeyunBae** [comment]
![image](https://user-images.githubusercontent.com/46209590/88643555-cbef1200-d0fc-11ea-8410-f64a82ea54fc.png)

**Comment by ChaeyunBae** [comment]
<img width="1456" alt="스크린샷 2020-07-30 오후 3 30 48" src="https://user-images.githubusercontent.com/46209590/88889349-ec44db00-d27a-11ea-9105-da5b1f4be539.png">
<img width="1484" alt="스크린샷 2020-07-30 오후 3 31 04" src="https://user-images.githubusercontent.com/46209590/88889356-efd86200-d27a-11ea-9276-2d29dab5bf0b.png">

**Comment by khw7096** [comment]
퍼블리쉬 하고 chrome에서 개발자 모드로 소스코드 고쳐가면서 디버그 하면 금방 찾을 수 있어요. 다음주에 같이해봐요.

**Comment by ChaeyunBae** [comment]
![image](https://user-images.githubusercontent.com/46209590/88906680-b27fce80-d292-11ea-898a-e9da1d318b8e.png)

**Comment by khw7096** [comment]
전체적인 느낌이 이뻐요~
