### ISSUE TITLE
maya upload bug 제 노트북에서는 연산이 되지 않습니다.

### ISSUE THREAD

**Issue by sar9702** [RD101/dotori#808]

**Comment by sar9702** [comment]
aerim.shim@shim-aerim-ui-MacBookAir dotori % ./dotori -http :80             
Service start: http://172.18.18.51
dotori: 2020/06/03 14:20:54 process.go:79: signal: segmentation fault

**Comment by sar9702** [comment]
ffmpeg 연산시 ffmpeg 자체가 연산되지 않는 문제.

**Comment by sar9702** [comment]
수동으로 해보겠습니다.

**Comment by sar9702** [comment]
연산폴더에 들어가면 .ogg 를 만들때 에러가 발생한다.

**Comment by sar9702** [comment]
실제 쉘에서 수동으로 타이핑 했다.
```bash
Press [q] to stop, [?] for help
zsh: segmentation fault  ffmpeg -y -i ./thumbnail.mov -c:v libtheora -qscale:v 7 -vf  -an test.ogg
aerim.shim@shim-aerim-ui-MacBookAir originalthumbmov % 
```

**Comment by sar9702** [comment]
bash쉘로 해봄.

```bash
Segmentation fault: 11
```

**Comment by sar9702** [comment]
brew 에서 언인스톨 하고 다시 깔아봄.

**Comment by sar9702** [comment]
os버전: 10.15.3

**Comment by sar9702** [comment]
한웅: 제 os는 10.15.4 이고 잘 연산이 되어요. os를 한번 업데이트 해봐봐용.

**Comment by sar9702** [comment]
업데이트해서 10.15.5가 됬는데 여전히 segmentation fault 에러가 나네요ㅠㅠㅠ

**Comment by khw7096** [comment]
그럼 brew 자체를 지워보고 ffmpeg를 깔아보는건 어때요?

**Comment by sar9702** [comment]
brew 재설치하고 ffmpeg 다시 설치하니깐 됬어요!!!!

![image](https://user-images.githubusercontent.com/14924389/83706065-801a7200-a651-11ea-9f32-b46f4d8de5e1.png)

**Comment by khw7096** [comment]
호우루우~~~~~
