### ISSUE TITLE
example: openVDB 업로드

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#818]

**Comment by khw7096** [comment]
https://www.youtube.com/watch?v=3nKXOZvc-Gk

블랜더 지원시작. 1분25초 부분

**Comment by khw7096** [comment]
https://www.openvdb.org/download/

위에서 가벼운 샘플파일을 하나 선택하고 예제로 올릴것

**Comment by ChaeyunBae** [comment]
1mb 짜리 하나 올릴까요??

**Comment by ChaeyunBae** [comment]
그리고 openvdb의 데이터는 .vdb 확장자 하나면 될까요?!

**Comment by khw7096** [comment]
네
