### ISSUE TITLE
프로세스 진행 중 에러가 난 경우 로그처리

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#824]

**Comment by khw7096** [comment]
1안: 마지막 로그만 보이도록 한다. / 당장 적용가능.

**Comment by baesy0** [comment]
에러가 난 경우의 status를 error로 할 경우 어디서 에러가 났는지 알 수 없으니
페이지에서 로그를 보여줄 필요가 있을 거 같아요

**Comment by baesy0** [comment]
그러면 마지막 로그를 보이게 해두고, 나중에 더 개선하도록 합시당

**Comment by khw7096** [comment]
좋습니다.
