### ISSUE TITLE
썸네일이 필요없는 파일의 처리

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#847]
https://github.com/RD101/dotori/blob/736bdac10c1d1d98839a9a34b04a080deaf1a91b/http_footage.go#L128

footage파일 업로드 부분을 보다가 든 생각인데요.
현재 handleUploadFootageItem에서 아래처럼 설정하고 있어요.
```go
item.ThumbImgUploaded = true  // footage 데이터는 이미지 썸네일 정보를 담고 있다.
item.ThumbClipUploaded = true // footage 데이터를 이용해서 썸네일 클립을 만들 수 있다.
item.DataUploaded = false
```
썸네일이 아직 생긴 건 아니니까 여기서는 false로 지정하고 실제로 썸네일이 생성되었을 때 바꾸는 게 좋을 거 같아요.

어차피 handleUploadFootageFile에서 DataUploaded만 체크하니까 나중에 썸네일이 실제로 생성되었을 때 바꿔도 상관없을 거 같구요
```go
if item.DataUploaded {
	item.Status = "fileuploaded"
}
```

**Comment by baesy0** [comment]
썸네일 업로드가 필요없는 파일
- sound 
- footage
- pdf
- hwp

**Comment by khw7096** [comment]
동의~!

**Comment by baesy0** [comment]
footage 내가 해줌
나중에 까까 사줘여

**Comment by khw7096** [comment]
동의~!
