### ISSUE TITLE
도토리 소개영상

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#860]
#### 편집순서
- [x] 타이틀
    - 대사: 안녕하세요. 에셋 라이브러리 시스템, 도토리를 소개합니다.
    - 자막: Asset Library System: Dotori
- [x] 소개
    - 대사: 도토리는 에셋을 체계적으로 관리할 수 있게 도와주는 웹 애플리케이션 서버입니다. 기업의 모든 사람들이 무형자산을 등록, 검색, 관리할 수 있습니다.
    - 자막:  
- [x] 특징
    - 대사: 도토리는 오픈소스 라이브러리와 웹 표준기술을 이용하여 제작되고 있습니다. 이 특징으로 인해 핸드폰, 패드형태의 디바이스, 웹 브라우저를 가리지 않고 사용 가능하며, 검색과 태그 시스템을 기반으로 운용되는 에셋 라이브러리 웹 애플리케이션 서버입니다.
    - 자막:
- [x] 지원 포맷 설명
    - 대사: 콘텐츠 제작회사에서 사용하는 대부분의 포멧을 등록할 수 있습니다. 만약 새로운 포맷을 추가하고 싶다면 2-3주 내로 기능을 개발하여 등록할 수 있습니다.
    - 자막:
- [x] 등록예제 하나를 추가하기
    - 대사: 간단하게 Autodesk사 마야 데이터를 등록하는 방법을 시연해 보겠습니다. 
    - 자막:
- [x] 프로세스 창 추가
    - 대사: 에셋을 등록하면 에셋 관리에 필요한 데이터를 생성하는 프로세스가 진행됩니다. 프로세스 페이지에서 각 에셋의 프로세스 진행 상태를 살펴볼 수 있습니다. 또한 회사 내부에서 운용하고 있는 스토리지 용량도 실시간으로 체크할 수 있습니다.
    - 자막:
- [x] 검색에 대한 설명 추가
    - 대사: 우리가 등록한 에셋을 검색해보겠습니다. 기본적으로 검색어를 검색창에 타이핑하여 검색할 수 있습니다. 에셋을 등록한 사람을 검색하고 싶다면 author: 로 검색하는 기능을 지원하며, 같은 방식으로 tag, attribute 키 값도 지원이 가능합니다.
    - 자막:
- [x] 관리자 설정페이지
    - 대사: 에셋 관리 서비스를 운영하기 위해서는 몇 가지 기술적인 설정이 필요합니다. 서비스를 운용할 때 필요한 모든 값은 Admin 메뉴를 통해서 설정 및 운용할 수 있습니다. 이 설정메뉴를 통해서 회사의 상황에 맞게 유동적으로 설정값을 관리할 수 있습니다.
    - 자막:
- [x] 데이터베이스 정리기능
    - 대사: 업로드 과정에서 예상치 못하게 생성되는 불필요한 데이터를 삭제할 수 있는 페이지입니다. 에셋으로서 가치가 없는 데이터를 삭제하여 데이터베이스를 효율적으로 관리할 수 있습니다.
    - 자막:
- [x] Rest API
    - 대사: 현재 개발중인 RestAPI 기능을 소개합니다. Dotori는 어떠한 프로그래밍 언어에서도 사용할 수 있도록 RestAPI를 지원합니다. 콘텐츠 제작에 사용되는 툴들은 Python, C#, C++ 언어들를 많이 사용하고 있으며 우리가 데모했던 기능들을 프로그래밍 언어와 RestAPI로도 조작할 수 있습니다. 앞으로도 각 기능들을 보완해가며 RestAPI를 늘려갈 생각입니다.
- [x] 권한과 토큰
    - 대사: 사용자마다 액세스 레벨을 설정할 수 있습니다. 각 유저마다 권한을 부여할 수 있습니다. 또한 부여된 권한은 암호화 하여 토큰을 생성하고 방금 소개해드린 RestAPI의 권한를 처리할 때 사용됩니다.
- [x] 마무리 인사
    - 대사: 지금까지 에셋 라이브러리 시스템의 간략한 기술데모였습니다. 앞으로 더 많은 기능이 추가될 예정입니다. 도토리의 미래를 기대해주세요!
    - 자막:

#### 담당
- 글: Jason, Bailey
- 다빈치 리졸브: Jason
- 데모영상 준비: Bailey

#### 포멧
- ProresHQ422
- 1920x1080
- ref: https://youtu.be/ZZzZC9-7PUc / 트렌지션 참고자료 후반

**Comment by khw7096** [comment]
- 소개 음성 녹음
- 자막, 대사
- 기획 1차 맞추어보기

**Comment by baesy0** [comment]
#### 동영상 캡쳐
mac에서 기본적으로 제공하는 동영상 캡쳐 사용
`command + shift + 5`
https://support.apple.com/ko-kr/HT208721

**Comment by baesy0** [comment]
#### 동영상 편집
- Davinci Resolve 16
- App store에서 무료로 다운
- https://www.blackmagicdesign.com/kr/products/davinciresolve/

**Comment by khw7096** [comment]
배경음악 선정

**Comment by baesy0** [comment]
마우스 포인터가 잘 보이도록 확대하여 진행하기
https://support.apple.com/ko-kr/guide/mac-help/mchlp2920/mac

**Comment by khw7096** [comment]
대사 작성완료.

**Comment by khw7096** [comment]
https://github.com/lazypic/ardour/blob/master/README.md

사운드 음원구매 체크 완료.

**Comment by khw7096** [comment]
1차영상이 작업되어서 이 이슈를 닫습니다.
