### ISSUE TITLE
adminsetting에서 이미지와 동영상의 썸네일 크기를 따로 지정하는 이유가 있나요?

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#874]
이미지든 동영상이든 썸네일 크기는 다 똑같아야 할 거 같아서요
관련 이슈:  #869

**Comment by baesy0** [comment]
adminsetting에서 지정하는 동영상의 가로 세로크기는 썸네일과는 무관하다.
이름을 바꿀 필요가 있다.

**Comment by baesy0** [comment]
`ContainerHeight`
`ContainerWidth`

**Comment by baesy0** [comment]
바꿔야 할 부분
- struct
- adminsetting페이지 문구
- ffmpeg연산하는 부분

**Comment by khw7096** [comment]
동의~!
