### ISSUE TITLE
linux go 개발 환경 세팅 방법 README 추가

### ISSUE THREAD

**Issue by ChaeyunBae** [RD101/dotori#895]
Linux(centos7.4)에서 GOBIN을 PATH에 추가하니까 
```bash
$ dotori
```
는 실행되는데
```bash
$ sudo dotori
```
는 실행 안 됨

**Comment by ChaeyunBae** [comment]
https://brownbears.tistory.com/252

**Comment by ChaeyunBae** [comment]
이거 근데 README에 추가할까요 말까요???

**Comment by khw7096** [comment]
sudo 권한문제는 도토리랑 별도의 문제니까 따로 진행하는게 어때요?

**Comment by khw7096** [comment]
간단하게 추가할 수 있다몀 추가합시다.
