### ISSUE TITLE
item 정보 edit 시에도 에러 체크 필요

### ISSUE THREAD

**Issue by ChaeyunBae** [RD101/dotori#902]
add item page에서는 항복별로 알맞은 정보가 들어갔는지 체크해주는 함수가 있었는데 edit에는 안들어가있어요! 
editpage에서도 item 정보들 잘 들어갔는지 확인해주는 기능 추가해야할 것 같습니다

![edit_checkerr](https://user-images.githubusercontent.com/46209590/86344594-68a4c800-bc95-11ea-8c47-f5c05d398291.png)
![success](https://user-images.githubusercontent.com/46209590/86344605-6c384f00-bc95-11ea-82c0-19c64ae08335.png)
![item](https://user-images.githubusercontent.com/46209590/86344736-95f17600-bc95-11ea-9ccb-e4cef8824653.png)

**Comment by baesy0** [comment]
item이 무엇을 의미하는지 잘 모르겠어요!
태그를 말하는 건가요?

**Comment by ChaeyunBae** [comment]
> item이 무엇을 의미하는지 잘 모르겠어요!
> 태그를 말하는 건가요?

앗 제가 너무 불친절하게 설명해놨네요! 아이템 정보들 말한 거였어요! add item 할 때처럼 CheckError() 함수 추가해주면 될 것 같아용

**Comment by ChaeyunBae** [comment]
- [] maya
