### ISSUE TITLE
footage: 프로세스중 나오는 에러 처리

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#904]
![image](https://user-images.githubusercontent.com/1149996/86420187-bc082c00-bd10-11ea-9505-88e479d4d7c3.png)

위 형태의 에러를 처리하면 에러가 발생하고 SetStatus 에러 처리시, 아래와 같은 에러 발생

![image](https://user-images.githubusercontent.com/1149996/86420238-de9a4500-bd10-11ea-96bf-b22a6b0462b9.png)

**Comment by khw7096** [comment]
좀더 심플한 에러처리를 먼저 할 것

**Comment by khw7096** [comment]
Footage 부분을 손보면서 웹서버가 안정적인 상황이 만들어지도록 가이드 코드를 진행해볼께요.

**Comment by khw7096** [comment]
FindOneAndUpdate 가 SetStatus에도 쓰이고 SetLog에도 FindOneAndUpdate가 쓰인다. 동시에 셋팅하는 함수를 만드는 것이 좋아보인다.

**Comment by khw7096** [comment]
실제로 코드를 관찰해보니 process.go 90번째줄 case문 에서만 SetStatus, SetLog를 처리하고 실제 내부 연산에서는 err 만 리턴해야 전체 구조에 문제가 없을 것 같습니다.

**Comment by baesy0** [comment]
> 실제로 코드를 관찰해보니 process.go 90번째줄 case문 에서만 SetStatus, SetLog를 처리하고 실제 내부 연산에서는 err 만 리턴해야 전체 구조에 문제가 없을 것 같습니다.

코드 봤어요! 훨씬 이쁜거 같아요👍
