### ISSUE TITLE
.hip, .hda, .blender 파일 업로드 안되는 문제

### ISSUE THREAD

**Issue by ChaeyunBae** [RD101/dotori#955]
mac에선 괜찮았는데 linux에서  .hip, .hda, .blender 파일을 업로드하면 허용하지 않는 파일 포맷이라고 뜹니다!
![image](https://user-images.githubusercontent.com/46209590/87529107-79a7fd00-c6c9-11ea-8d28-ddfd3f2d4e5d.png)

**Comment by ChaeyunBae** [comment]
mimeType 프린트 찍어보면 각각 아래와 같이 출력돼요
- ```x-blender```
- ```x-hip```
- ```x-hda```

**Comment by ChaeyunBae** [comment]
case를 추가하면 해결될 문제긴 한데 원인이 뭔지를 모르겠어요!

**Comment by khw7096** [comment]
실제로 타입은 웹 브라우저의 엔진마다 다르니, 위 타입을 추가해주면 됩니다. 파이어폭스를 사용했나요?

**Comment by ChaeyunBae** [comment]
아뇨 크롬에서 했어요!

**Comment by khw7096** [comment]
역시 구글은 최신 어플리케이션도 지원하기 위해서 여러 타입을 테스트하는 군요~!
