### ISSUE TITLE
.ies 썸네일 만들기

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#956]

**Comment by baesy0** [comment]
참고
https://github.com/nickmcdonald/ies-generator/blob/master/preview/preview.py

**Comment by baesy0** [comment]
IES 파일의 각 값이 의미하는 바
https://docs.agi32.com/AGi32/Content/references/IDH_iesna_standard_file_format.htm

**Comment by baesy0** [comment]
IES standard document
https://www.ies.org/standards/ies-lighting-library/

**Comment by khw7096** [comment]
이건 다른 기능에 비해서 아직 중요한 기능이 아니예요~(특히 콘텐츠 제작회사 입장에서..) 다른걸 먼저하는 것이 좋을것 같아요.

**Comment by baesy0** [comment]
ㅇㅇ금방 끝날줄 알았는데 좀 파보니까 오래걸릴 거 같아요. 일단 닫았다가 나중에 다시 진행할 때 열게요

**Comment by baesy0** [comment]
https://www.ies.org
