### ISSUE TITLE
items.html 부분

### ISSUE THREAD

**Issue by 78963l** [RD101/dotori#967]
56 줄에
    
    <script src="/assets/js/dotori.js"></script>

이부분이 필요한가요??

**Comment by khw7096** [comment]
기본 라이브러리 이외에 필요한 custom 자바스크립트 부분이예요. 필요한 부분이예요.

**Comment by kwonnahyunnnn** [comment]
메인페이지에서 중복으로 들어가서 여쭤봤어요

**Comment by 78963l** [comment]
메인페이지에서 중복으로 들어가서 여쭤봤어요

**Comment by khw7096** [comment]
중복이 된다면 중복되는 부분을 제거하는게 맞을것 같아요~ :-)

**Comment by 78963l** [comment]
넵 감사힙니다~
