### ISSUE TITLE
handleSearch함수나 go파일에 있는 함수들이 2번씩 도는것같은데 상관없나요??

### ISSUE THREAD

**Issue by 78963l** [RD101/dotori#974]

**Comment by khw7096** [comment]
그렇게 생각한 근거가 있다면 적어줄 수 있나요? 2번씩 돈다면 한번씩 도는걸로 바꾸어야 하니까요~!

**Comment by khw7096** [comment]
현재 검토할 PR이 끝나면 저도 handleSearch 함수를 Print 찍어보죠~!

**Comment by 78963l** [comment]
전부해본건아닌데 http_search.go 파일에서 print찍어보니깐 
<img width="554" alt="스크린샷 2020-07-20 오후 11 32 25" src="https://user-images.githubusercontent.com/46780796/87949777-6938bd80-cae1-11ea-8dee-7e5e4157cda5.png">
2번나와요

**Comment by 78963l** [comment]
> 현재 검토할 PR이 끝나면 저도 handleSearch 함수를 Print 찍어보죠~!

네넵 알겠습니다~

**Comment by khw7096** [comment]
그냥 아직 인덱스가 없어서 리다이렉트 되기 때문일것 같아요.
![image](https://user-images.githubusercontent.com/1149996/87950018-bb79de80-cae1-11ea-8758-206e9590f64f.png)

나중에 성민님이 만드는 index.html 만들면 사라지지 않을까요?

**Comment by 78963l** [comment]
아하! 감사합니다 ㅎㅎ

**Comment by khw7096** [comment]
넹넹

**Comment by khw7096** [comment]
일단 이 이슈는 어싸인이 성민님으로 되어있는데.. 진행하실 건가요?

**Comment by 78963l** [comment]
초기페이지 push 후에 진행해도 괜찮을까요??

**Comment by khw7096** [comment]
마음이 편한대로~해요~ 혹시 그 전에 처리되고 싶은 이슈라면~! 알려주어요~

개발자 명언중에...이런말이 있거든요~

"신 기능보다.. 버그를 먼저 고쳐라~"

**Comment by 78963l** [comment]
이유 : 브라우저가 /favicon.ico를 요청합니다. 이것은 catchall 핸들러 인 "/" 와 일치 하므로 두 번 호출됩니다.
해결방법 : 찾는중

**Comment by 78963l** [comment]
'''
<link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon">
'''
를 추가하여 요청을 피하라...

**Comment by 78963l** [comment]
헛 그러고보니 저희는 아이콘이 있네요.. 머때문이지

**Comment by baesy0** [comment]
와드박고 갑니다

**Comment by 78963l** [comment]
TEMPLATES.ExecuteTemplate 를 하는 함수들은 2번씩 돌고돌고

**Comment by 78963l** [comment]
전부주석처리하니깐 3번씩 돌고돌고돌고

**Comment by khw7096** [comment]
/favicon.ico 이건 모예요?

**Comment by khw7096** [comment]
일단 저는 1번만 뜹니다.

<img width="462" alt="image" src="https://user-images.githubusercontent.com/1149996/89016717-259d4980-d354-11ea-977e-59dcad85bb1e.png">

<img width="518" alt="image" src="https://user-images.githubusercontent.com/1149996/89016726-2a61fd80-d354-11ea-8a37-5ae317a92447.png">

<img width="534" alt="image" src="https://user-images.githubusercontent.com/1149996/89016738-3057de80-d354-11ea-92b4-b594f366cbd3.png">

**Comment by khw7096** [comment]
성민씨 어떤 브라우저에서 테스트하고 있나요?

**Comment by khw7096** [comment]
저는 사파리, 크롬, 파이어폭스 모두 1번씩 잘 뜨고 있습니다.

**Comment by 78963l** [comment]
<img width="735" alt="스크린샷 2020-08-04 오후 12 29 48" src="https://user-images.githubusercontent.com/46780796/89249847-37ca0100-d64e-11ea-83e0-76f9e6bd1f5a.png">
<img width="494" alt="스크린샷 2020-08-04 오후 12 29 38" src="https://user-images.githubusercontent.com/46780796/89249850-3b5d8800-d64e-11ea-8ce9-8444657a1c25.png">
<img width="635" alt="스크린샷 2020-08-04 오후 12 29 29" src="https://user-images.githubusercontent.com/46780796/89249853-3d274b80-d64e-11ea-8c6a-b5e48cae44d8.png">

**Comment by 78963l** [comment]
저는 크롬에서 하고있어요

**Comment by baesy0** [comment]
### 크롬
<img width="463" alt="image" src="https://user-images.githubusercontent.com/40417084/89250400-a491cb00-d64f-11ea-9f39-f6153490947d.png">

### 사파리
<img width="451" alt="image" src="https://user-images.githubusercontent.com/40417084/89250462-cab76b00-d64f-11ea-9307-e3c8832ea429.png">

**Comment by 78963l** [comment]
크롬에선 2번돌고 사파리에선 1번돌아요

**Comment by khw7096** [comment]
내일 같이 코드 봐봐요~!

**Comment by 78963l** [comment]
네넵!

**Comment by 78963l** [comment]
해결법 : 크롬에 있는 확장프로그램을 사용하지 않는다.
