### ISSUE TITLE
meta: unity(게임엔진)

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#987]
호밍쿤의 조언을 듣고 작성시작.

**Comment by khw7096** [comment]
호밍쿤의 조언을 듣고 작성시작.

**Comment by Squidward79** [comment]
<유니티에서 사용되는 확장자 명>

**.cs** - c#스크립트 파일 
**.unity** - 유니티의 씬 파일 
**.prefab** - 오브젝트의 각종 데이터를 패키지화 시켜둔 파일
**.asset** - 유니티에서 생성된 각종 파일들의 확장자( ex. 렌더링파이프라인 세팅, ScriptableObject 파일 등등)
**.anim, .controller** - 애니메이션과 애니메이션을 관리하는 컨트롤러에 대한 파일
**.shader** - 쉐이더 파일 
**.mat** - material 파일 

**.meta** - 리소스만 있으면 상관이 없으나 설정값 등 메타데이터까지 업로드해야 한다면 필요

**Comment by khw7096** [comment]
아니~~ 대 호밍쿤님이 글을 남겨주시다니~~~ 꾸벅~!

**Comment by baesy0** [comment]
@Squidward79 아이고오 감사합니다 호민님🙇
